// Actual healthy standing Fighter/Skill input protocol; research, not user-scene reproduction.
import {newRound,CONFIG,DT,THREE} from './harness_m.mjs';
import {isMain} from './is_main.mjs';
import {createHash} from 'node:crypto';
import {readFile,writeFile,readdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {performance} from 'node:perf_hooks';
const ROOT=new URL('../../',import.meta.url),WEAPONS=['sabre','rapier','tree_branch','falchion','qinggang','pistol','rubber_chicken','morgenstern','longsword','zweihander','estoc'];
const hash=x=>createHash('sha256').update(x).digest('hex'),v=x=>({x:x.x,y:x.y,z:x.z}),norm=x=>Math.hypot(x.x,x.y,x.z);
class Passive{update(){}}
function finite(x){if(typeof x==='number'&&!Number.isFinite(x))throw new Error('Nonfinite observation');if(x&&typeof x==='object')Object.values(x).forEach(finite);}
function point(b,a){return new THREE.Vector3(a.x,a.y,a.z).applyQuaternion(new THREE.Quaternion().copy(b.rotation())).add(new THREE.Vector3().copy(b.translation()));}
function state(f){return {state:f.state,stateTime:f.stateTime,blood:f.blood,limbs:{...f.limbs},armed:f.armed,gripping:f.gripping,handHeld:f.handHeld,inputActive:f.inputActive,handOffset:f.handOffset.toArray(),skill:{aim:f.skill.aim.toArray(),aimRaw:f.skill.aimRaw.toArray(),aimVel:f.skill.aimVel.toArray(),recovering:f.skill.recovering,cutPending:f.skill.cutPending},bodies:[...Object.entries(f.bodies),['sword',f.sword]].map(([name,b])=>({name,p:v(b.translation()),q:{...b.rotation()},vel:v(b.linvel()),omega:v(b.angvel()),mass:b.mass()})),joints:f.joints.map(j=>({name:j.name,target:j.target.toArray(),prevRV:j.prevRV?.toArray(),gain:j.gain??1})),gait:{active:f.gait.active,levH:f.gait.levH,levC:f.gait.levC}};}
function observation(f,timeS,phase,torque){const a=point(f.bodies.farmS,f.gripJoint.anchor1()),b=point(f.sword,f.gripJoint.anchor2()),fq=new THREE.Quaternion().copy(f.bodies.farmS.rotation()),sq=new THREE.Quaternion().copy(f.sword.rotation()),relative=fq.invert().multiply(sq),blade=point(f.sword,{x:0,y:1,z:0}).sub(new THREE.Vector3().copy(f.sword.translation()));return {timeS,phase,state:f.state,handHeld:f.handHeld,inputActive:f.inputActive,armed:f.armed,gripping:f.gripping,recovering:f.skill.recovering,handOffset:f.handOffset.toArray(),aim:f.skill.aim.toArray(),actualWristWorldM:v(a),actualGripWorldM:v(b),gripAnchorGapM:a.distanceTo(b),swordRelativeForearmQuaternion:relative.toArray(),swordAngularVelocityRadps:v(f.sword.angvel()),bladeDirectionWorld:v(blade),swordUserTorqueBeforeSolverNm:torque,debugWristTorqueBeforeTwistNm:v(f.debug.wristTorque),debugWristCapNm:f.debug.wristCap??null,pelvisHeightM:f.bodies.pelvis.translation().y};}
function protocol(home){return [{name:'hold',duration:1,held:true,to:home},{name:'drag_high',duration:.7,held:true,to:[.25,.38]},{name:'hold_high',duration:.8,held:true},{name:'drag_low',duration:.7,held:true,to:[-.32,-.28]},{name:'hold_low',duration:.8,held:true},{name:'release',duration:1.5,held:false},{name:'reinput_hold',duration:.5,held:true},{name:'reinput_drag',duration:1,held:true,to:[.12,.15]},{name:'release_again',duration:1,held:false}];}
function run(weapon){const saved={assist:CONFIG.GAIT.assist,catchMode:CONFIG.GAIT.catchMode,catchScale:CONFIG.GAIT.catchScale,reaction:CONFIG.GRIP.reactionModel,support:CONFIG.BODY.supportModel,weight:CONFIG.BODY.weightMode},random=Math.random;let G;const row={weapon,seed:7,health:'normal, no wounds injected',status:'observed',samples:[],phases:[],frames:0};try{Object.assign(CONFIG.GAIT,{assist:.1,catchMode:'on',catchScale:1});CONFIG.GRIP.reactionModel='paired';CONFIG.BODY.supportModel='legacy';CONFIG.BODY.weightMode='hybrid';G=newRound({seed:7,walls:false,weapon,AIClass:Passive});G.park();const f=G.player;if(f.weapon.id!==weapon)throw new Error('Weapon ID fallback: '+weapon+' -> '+f.weapon.id);f.skill.autoGuard=true;f.handHeld=false;f.inputActive=false;for(let i=0;i<Math.round(3/DT);i++)G.step();if(f.state!=='stand')throw new Error('Preparation not standing');row.startSha256=hash(JSON.stringify(state(f)));row.twoHand=f.weaponCfg.twoHand;row.oneHandStance=f.guardPose.oneHand;row.physicalGripJointHandle=String(f.gripJoint.handle);const trace=createHash('sha256'),input=createHash('sha256');let preTorque=null,time=0;const originalStep=G.world.step;G.world.step=function(...args){preTorque=v(f.sword.userTorque());return originalStep.apply(this,args);};row.max={gripAnchorGapM:0,swordAngularSpeedRadps:0,swordUserTorqueMagnitudeNm:0};row.peak=null;row.grippingFrames=0;row.recoveringFrames=0;const phases=protocol(f.handOffset.toArray());row.protocol=phases;
outer:for(const phase of phases){const start=f.handOffset.toArray(),count=Math.round(phase.duration/DT);row.phases.push({phase:phase.name,startTimeS:time,frames:count});for(let i=0;i<count;i++){let dx=0,dy=0;if(phase.to){const u=(i+1)/count,x=start[0]+(phase.to[0]-start[0])*u,y=start[1]+(phase.to[1]-start[1])*u;dx=x-f.handOffset.x;dy=y-f.handOffset.y;if(!f.weapon.gun){f.handOffset.x+=dx;f.handOffset.y+=dy;}}f.handHeld=phase.held;f.inputActive=Math.abs(dx)+Math.abs(dy)>1e-5;f.move.set(0,0);input.update(JSON.stringify({phase:phase.name,dx,dy,held:f.handHeld,active:f.inputActive}));G.step();time+=DT;row.frames++;const s=state(f),o=observation(f,time,phase.name,preTorque);finite(s);finite(o);trace.update(JSON.stringify(s));row.grippingFrames+=+f.gripping;row.recoveringFrames+=+f.skill.recovering;if(o.gripAnchorGapM>row.max.gripAnchorGapM){row.max.gripAnchorGapM=o.gripAnchorGapM;row.peak=o;}row.max.swordAngularSpeedRadps=Math.max(row.max.swordAngularSpeedRadps,norm(f.sword.angvel()));row.max.swordUserTorqueMagnitudeNm=Math.max(row.max.swordUserTorqueMagnitudeNm,norm(preTorque));if(i===0||i===count-1||row.frames%24===0)row.samples.push(o);if(f.state!=='stand'){row.status='left_standing_scope';row.stop=o;break outer;}}}
row.traceSha256=trace.digest('hex');row.inputSha256=input.digest('hex');row.final=state(f);row.finite=true;row.gripJointStillExists=!!G.world.getImpulseJoint(f.gripJoint.handle);row.elapsedS=time;row.expectedFrames=phases.reduce((n,p)=>n+Math.round(p.duration/DT),0);row.pass=row.frames===row.expectedFrames&&row.finite&&row.gripJointStillExists&&(!row.twoHand?row.grippingFrames===0:true);
}catch(e){row.status='error';row.error=e.stack;row.pass=false;}finally{G?.eventQueue.free();G?.world.free();Math.random=random;Object.assign(CONFIG.GAIT,{assist:saved.assist,catchMode:saved.catchMode,catchScale:saved.catchScale});CONFIG.GRIP.reactionModel=saved.reaction;CONFIG.BODY.supportModel=saved.support;CONFIG.BODY.weightMode=saved.weight;}return row;}
async function main(){const o={};for(const a of process.argv.slice(2)){const m=/^--(out|compare)=(.+)$/.exec(a);if(!m)throw new Error('Use --out=PATH [--compare=BASELINE_JSON]');o[m[1]]=m[2];}async function sourceFiles(dir){const es=await readdir(new URL(dir,ROOT),{withFileTypes:true});const xs=[];for(const e of es){const p=dir+'/'+e.name;if(e.isDirectory())xs.push(...await sourceFiles(p));else if(e.name.endsWith('.js'))xs.push(p);}return xs;}const manifest=async()=>Object.fromEntries(await Promise.all([...await sourceFiles('src'),'tools/sim/harness_m.mjs','tools/sim/onehand_guard_probe.mjs'].sort().map(async p=>[p,hash(await readFile(new URL(p,ROOT)))])));const before=await manifest(),begin=performance.now(),rows=WEAPONS.map(run),after=await manifest(),result={schemaVersion:1,probe:'onehand_guard_probe',sourceCommit:execFileSync('git',['rev-parse','HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),sourceSha256:before,sourceSha256After:after,sourceStableDuringRun:JSON.stringify(before)===JSON.stringify(after),wallSeconds:(performance.now()-begin)/1000,protocol:'Native Fighter/Skill held/inputActive and handOffset deltas follow main frame hand input contract, no renderer/input event injection. B paired legacy, seed7,3s preparation,8s protocol; healthy standing only. Touch release is not physical dropSword. Actual user symptom is not proved reproduced.',torqueDefinition:'sword.userTorque captured read-only immediately before native solver: total explicit controller torque, including any point-force moments; debug wrist torque is before twist, not final applied wrist torque.',rows};if(o.compare){const baseline=JSON.parse(await readFile(o.compare,'utf8'));result.comparison=rows.map(r=>{const b=baseline.rows.find(b=>b.weapon===r.weapon);return {weapon:r.weapon,startIdentical:r.startSha256===b?.startSha256,inputIdentical:r.inputSha256===b?.inputSha256,traceIdentical:r.traceSha256===b?.traceSha256,twoHandExactRequired:r.twoHand};});}const out=o.out||'/tmp/onehand-guard.json';await writeFile(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({out,wallSeconds:result.wallSeconds,sourceStable:result.sourceStableDuringRun,comparison:result.comparison,rows:rows.map(r=>({weapon:r.weapon,status:r.status,pass:r.pass,frames:r.frames,trace:r.traceSha256,grippingFrames:r.grippingFrames,max:r.max,error:r.error}))}));if(!result.sourceStableDuringRun||rows.some(r=>!r.pass)||result.comparison?.some(r=>r.twoHandExactRequired&&(!r.startIdentical||!r.inputIdentical||!r.traceIdentical)))process.exitCode=1;}
if(isMain(import.meta.url))main().catch(e=>{console.error(e.stack);process.exitCode=1;});
