// Actual native Rapier contact fixtures + actual game getter on/off trace.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {performance} from 'node:perf_hooks';
import {fileURLToPath} from 'node:url';
import {newRound,RAPIER,THREE,DT} from './harness_m.mjs';
import {collectSupportContacts} from '../../src/support_contacts.js';
const repo=fileURLToPath(new URL('../../',import.meta.url)),tests=[];
const coreFiles=['src/fighter.js','src/gait.js','src/config.js','src/combat.js','tools/sim/harness_m.mjs'];
const hashes=()=>Object.fromEntries(coreFiles.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(repo+'/'+p)).digest('hex')]));
const sourceBefore=hashes(),start=performance.now();
const near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<=e,`${a} differs from ${b}`);
function test(name,run){try{const details=run();tests.push({name,pass:true,details});console.log('PASS',name);}catch(e){tests.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);}}
function fixture({groundFirst=true,groundType='fixed',sensor=false,y=.1,gravity=-9.81,offset=false,iters=6}={}){
 const world=new RAPIER.World({x:0,y:gravity,z:0});world.timestep=DT;world.integrationParameters.numSolverIterations=iters;let body,floor,own,ground;
 const floorFn=()=>{const desc=groundType==='kinematic'?RAPIER.RigidBodyDesc.kinematicPositionBased():groundType==='dynamic'?RAPIER.RigidBodyDesc.dynamic():RAPIER.RigidBodyDesc.fixed();floor=world.createRigidBody(desc.setTranslation(0,-.5,0));ground=world.createCollider(RAPIER.ColliderDesc.cuboid(1,.5,1).setSensor(sensor).setMass(100),floor);};
 const bodyFn=()=>{const q=offset?new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),.4):new THREE.Quaternion();body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,y+(offset?.1*Math.cos(.4):0),0).setRotation(q));own=world.createCollider(RAPIER.ColliderDesc.ball(.1).setMass(2).setTranslation(0,offset?-.1:0,0),body);};
 if(groundFirst){floorFn();bodyFn();}else{bodyFn();floorFn();}
 const f={world,bodies:{footF:body},colliderInfo:new Map(),detachedParts:new Set()};
 const step=n=>{for(let i=0;i<n;i++)world.step();};return {world,body,floor,own,ground,f,step,free:()=>world.free()};
}
test('normal points toward selected body in both native manifold orders',()=>{
 const rows=[];for(const groundFirst of [true,false]){const x=fixture({groundFirst});try{x.step(30);const r=collectSupportContacts(x.f),c=r.groups.footF.contacts[0];assert.ok(r.groups.footF.hasSupport);near(c.normalTowardBody.y,1);near(c.normalTowardBody.x,0);assert.equal(c.flipped,groundFirst);assert.ok(c.fixed&&!c.kinematic);near(c.geometryContacts[0].pointEnvironment.y,0);near(c.rawNormalImpulseOnBodyNs.y+c.rawNormalImpulseOnEnvironmentNs.y,0);rows.push({groundFirst,solverIterations:r.solverIterations,flipped:c.flipped,normalRaw:c.normalRaw,normalTowardBody:c.normalTowardBody,rawNormalImpulseNs:c.rawNormalImpulseNs,rawNormalForceN:c.rawNormalForceN,expectedMgN:2*9.81,calibrationApplied:c.calibrationApplied});assert.equal(c.calibrationApplied,false);near(r.groups.footF.rawNormalImpulseNs,c.rawImpulseEntries.reduce((s,a)=>s+a.normalImpulseNs,0));}finally{x.free();}}return rows;
});
test('collider local offset/rotation yields world surface points',()=>{const x=fixture({offset:true});try{x.step(30);const c=collectSupportContacts(x.f).groups.footF.contacts[0],current=x.own.contactCollider(x.ground,1e-4);assert.ok(c.hasSupport&&current);near(c.geometryContacts[0].pointBody.y,current.point1.y,1e-6);near(c.geometryContacts[0].pointEnvironment.y,current.point2.y,1e-6);near(c.geometryContacts[0].freshNormalGapM,current.distance,1e-6);return {pointBody:c.geometryContacts[0].pointBody,pointEnvironment:c.geometryContacts[0].pointEnvironment,freshGap:c.geometryContacts[0].freshNormalGapM};}finally{x.free();}});
test('no narrow-phase contact is false despite low body height',()=>{const x=fixture({gravity:0});try{const r=collectSupportContacts(x.f);assert.equal(r.anySupport,false);assert.equal(r.anyEnvironmentTouch,false);assert.equal(r.groups.footF.contacts.length,0);return {bodyY:x.body.translation().y,contactCount:0};}finally{x.free();}});
test('prediction contact is recorded separately and rejected outside slop',()=>{const x=fixture({gravity:0,y:.1005});try{x.step(1);const r=collectSupportContacts(x.f),c=r.groups.footF.contacts[0];assert.ok(c,'Expected native prediction manifold');assert.ok(c.minimumSolverDistanceM>r.contactSlopM);assert.ok(c.solverPoints.every(p=>p.predictionContact));assert.equal(c.hasSupport,false);assert.equal(r.anySupport,false);return {solverDistance:c.minimumSolverDistanceM,slop:r.contactSlopM,rawNormalImpulseNs:c.rawNormalImpulseNs,engineTouching:c.engineTouching};}finally{x.free();}});
test('floor collider removal cannot retain last raw impulse as support',()=>{const x=fixture();try{x.step(30);assert.ok(collectSupportContacts(x.f).anySupport);x.world.removeCollider(x.ground,true);const r=collectSupportContacts(x.f);assert.equal(r.anySupport,false);assert.equal(r.groups.footF.contacts.length,0);assert.equal(r.groups.footF.rawNormalImpulseNs,0);return {afterRemoval:r.groups.footF};}finally{x.free();}});
test('normal separation rejects stale manifold and deferred collider pose',()=>{const x=fixture();try{x.step(30);const before=collectSupportContacts(x.f);assert.ok(before.anySupport);x.body.setTranslation({x:0,y:1,z:0},true);const nativeColliderY=x.own.translation().y,r=collectSupportContacts(x.f),c=r.groups.footF.contacts[0];assert.ok(c,'Retained engine manifold should remain visible as rejected evidence');assert.ok(c.posesUnsynchronized);assert.ok(c.minimumFreshGapM>.8);assert.equal(r.anySupport,false);assert.equal(r.groups.footF.rawNormalImpulseNs,0);assert.ok(c.rawNormalImpulseNs>0);return {bodyY:x.body.translation().y,nativeColliderY,oldRawImpulseNs:c.rawNormalImpulseNs,currentFreshGapM:c.minimumFreshGapM,support:r.anySupport,queries:r.diagnostics};}finally{x.free();}});
test('lateral separation also rejects stale manifold after collider pose propagation',()=>{const x=fixture();try{x.step(30);x.body.setTranslation({x:3,y:x.body.translation().y,z:0},true);x.world.propagateModifiedBodyPositionsToColliders();const r=collectSupportContacts(x.f),c=r.groups.footF.contacts[0];assert.ok(c);assert.equal(c.posesUnsynchronized,false);assert.ok(c.tangentGeometryStale);assert.ok(c.freshShapeNeeded);assert.equal(c.freshShapeWithinSlop,false);assert.equal(r.anySupport,false);return {freshGapM:c.minimumFreshGapM,tangentGeometryStale:c.tangentGeometryStale,currentShapeContact:c.currentShapeContact,queries:r.diagnostics};}finally{x.free();}});
test('dynamic opponent, fixed fighter collider, sensor and detached limb are not ground support',()=>{const rows=[];for(const mode of ['dynamic','fixed_fighter','sensor','detached']){const x=fixture({gravity:0,groundType:mode==='dynamic'?'dynamic':'fixed',sensor:mode==='sensor'});try{x.step(1);if(mode==='fixed_fighter')x.f.colliderInfo.set(x.ground.handle,{fighter:{name:'opponent'}});if(mode==='detached')x.f.detachedParts.add('footF');const r=collectSupportContacts(x.f);assert.equal(r.anySupport,false);assert.equal(r.anyEnvironmentTouch,false);rows.push({mode,contacts:r.groups.footF.contacts.length,detached:r.groups.footF.detached});}finally{x.free();}}return rows;
});
test('wall contact is environment touch but not vertical support',()=>{
 const world=new RAPIER.World({x:0,y:0,z:0});world.timestep=DT;const floor=world.createRigidBody(RAPIER.RigidBodyDesc.fixed());world.createCollider(RAPIER.ColliderDesc.cuboid(.5,2,2).setTranslation(-.5,0,0),floor);const b=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(.099,0,0));world.createCollider(RAPIER.ColliderDesc.ball(.1).setMass(2),b);world.step();try{const r=collectSupportContacts({world,bodies:{footF:b},colliderInfo:new Map()}),c=r.groups.footF.contacts[0];assert.ok(r.anyEnvironmentTouch);assert.equal(r.anySupport,false);near(c.normalAlignmentWithUp,0);return {normalTowardBody:c.normalTowardBody,alignment:c.normalAlignmentWithUp};}finally{world.free();}
});
test('kinematic environment and contact-point velocity are measured explicitly',()=>{const x=fixture({groundType:'kinematic'});try{x.step(30);x.floor.setNextKinematicTranslation({x:.002,y:-.5,z:0});x.step(1);const r=collectSupportContacts(x.f),c=r.groups.footF.contacts[0],p=c.solverPoints[0];assert.ok(c.kinematic&&c.hasSupport);near(p.pointVelocityEnvironment.x,.002/x.world.timestep,1e-5);const original=x.body.velocityAtPoint(p.point);near(p.pointVelocityBody.x,original.x,1e-6);return {environmentType:c.environmentBodyType,point:p.point,bodyVelocity:p.pointVelocityBody,environmentVelocity:p.pointVelocityEnvironment,relativeTangentialSpeedMps:p.relativeTangentialSpeedMps};}finally{x.free();}});
test('foot, shin and forearm-proxy groups retain separate native evidence',()=>{
 const world=new RAPIER.World({x:0,y:-9.81,z:0});world.timestep=DT;const floor=world.createRigidBody(RAPIER.RigidBodyDesc.fixed());world.createCollider(RAPIER.ColliderDesc.cuboid(5,.5,5).setTranslation(0,-.5,0),floor);const bodies={};for(const [i,part] of ['footF','footB','shinF','shinB','farmO'].entries()){const b=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(i*.5,.1,0));world.createCollider(RAPIER.ColliderDesc.ball(.1).setMass(1),b);bodies[part]=b;}for(let i=0;i<30;i++)world.step();try{const r=collectSupportContacts({world,bodies,colliderInfo:new Map()});for(const g of Object.values(r.groups))assert.ok(g.hasSupport&&g.contacts.length>0);assert.ok(r.groups.handO.proxy.includes('forearm'));return Object.fromEntries(Object.entries(r.groups).map(([n,g])=>[n,{parts:g.parts,hasSupport:g.hasSupport,rawImpulse:g.rawNormalImpulseNs,proxy:g.proxy}]));}finally{world.free();}
});
test('detail:false and conditional shape query match always-fresh reference without changing actual game trace',()=>{
 class Passive{update(){}}
 function run(observed){const G=newRound({seed:7,walls:false,AIClass:Passive});G.park();G.before=t=>{G.player.move.set(.25*Math.sin(t*2),.1);};let getterMs=0,queries=0,manifolds=0,referenceChecks=0;const trace=crypto.createHash('sha256'),begin=performance.now();for(let i=0;i<360;i++){G.step();if(observed){const t=performance.now(),r=collectSupportContacts(G.player,{detail:false});getterMs+=performance.now()-t;queries+=r.diagnostics.freshShapeQueries;manifolds+=r.diagnostics.manifolds;if(i%30===0){const ref=collectSupportContacts(G.player,{verifyCurrentShape:'always'});for(const k of Object.keys(r.groups))assert.equal(r.groups[k].hasSupport,ref.groups[k].hasSupport,`${k} differs from always-fresh reference at frame ${i}`);assert.ok(r.groups.footF.contacts.every(c=>!('solverPoints' in c)));referenceChecks++;}}trace.update(JSON.stringify([G.player,G.enemy].map(f=>({state:f.state,blood:f.blood,bodies:[...Object.values(f.bodies),f.sword].map(b=>[b.mass(),b.translation(),b.rotation(),b.linvel(),b.angvel()])}))));}const result={wallSeconds:(performance.now()-begin)/1000,getterMs,queries,manifolds,referenceChecks,sha:trace.digest('hex')};G.eventQueue.free();G.world.free();return result;}
 // Warm the actual engine before wall comparison; this is not a mobile/browser benchmark.
 const warm=run(false),off=run(false),on=run(true);assert.equal(on.sha,off.sha);assert.equal(warm.sha,off.sha);return {frames:360,off,on,traceExact:true,getterAverageMs:on.getterMs/360,limitation:'Single desktop Node run; no mobile throughput claim, no controller change, native getter reference read only.'};
});
const result={createdUTC:new Date().toISOString(),pass:tests.every(t=>t.pass),tests,sourceBefore,sourceAfter:hashes(),moduleSHA:crypto.createHash('sha256').update(fs.readFileSync(repo+'/src/support_contacts.js')).digest('hex'),totalWallSeconds:(performance.now()-start)/1000};result.sourceStable=JSON.stringify(result.sourceBefore)===JSON.stringify(result.sourceAfter);result.pass&&=result.sourceStable;const out=process.argv[2]||'/tmp/halfsword-support-contacts.json';fs.writeFileSync(out,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pass:result.pass,count:tests.length,failed:tests.filter(t=>!t.pass).map(t=>t.name),sourceStable:result.sourceStable,totalWallSeconds:result.totalWallSeconds,out}));process.exitCode=result.pass?0:1;
