import fs from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const researchRoot=path.resolve(process.env.ENGINE_RESEARCH_ROOT||'/tmp/halfsword-engine-research');
const gameRoot=fileURLToPath(new URL('../../',import.meta.url));
if(researchRoot==='/'||researchRoot===gameRoot.replace(/\/$/,'')||researchRoot.startsWith(gameRoot))throw Error('ENGINE_RESEARCH_ROOT must be outside game');
const moduleURL = pathToFileURL(path.join(researchRoot,'rapier.js/rapier-compat/builds/3d/pkg/rapier.mjs'));
const {default:R} = await import(moduleURL.href);
await R.init();
const names=['init','World','RigidBodyDesc','ColliderDesc','JointData'];
for(const name of names) if(typeof R[name]!=='function') throw Error(`missing high-level ${name}`);
const w=new R.World({x:0,y:-9.81,z:0});
const rb=w.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(0,2,0));
w.createCollider(R.ColliderDesc.ball(.2),rb);
const methods=['jointSetMotorMaxForce','jointMotorMaxForce','jointSetMotorEnabled','jointMotorEnabled','jointMotorImpulse'];
for(const name of methods) if(typeof w.impulseJoints.raw[name]!=='function') throw Error(`missing native ${name}`);
w.step();
const result={ok:true,module:fileURLToPath(moduleURL),version:R.version(),highLevel:names,rawMethods:methods,oneStepPosition:rb.translation(),gravity:w.gravity,externalWasmRequired:false};
w.free();
fs.writeFileSync(path.join(researchRoot,'evidence/import-smoke.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result));
