// Native card entry, canonical weapon identity, touch input and restart. No combat/RNG overrides.
// --expect=baseline|fixed --out=/fresh/evidence-directory [--base=http://127.0.0.1:4173/]
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),own='tools/browser/phase4_weapon_identity_20261008.mjs';
const args=Object.fromEntries(process.argv.slice(2).map(v=>{const m=/^--(expect|out|base)=(.+)$/.exec(v);assert(m);return[m[1],m[2]];}));
assert(['baseline','fixed'].includes(args.expect));assert(args.out&&path.isAbsolute(args.out));
const artifactRoot='/workspace/halfsword-handoff/phase4-weapon-identity-20261008/browser',out=path.resolve(args.out);assert.equal(path.dirname(out),artifactRoot);
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/'),local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(local&&base.protocol==='http:'||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');assert(!base.search&&!base.hash&&!base.username&&!base.password&&base.pathname.endsWith('/'));
const sha=b=>createHash('sha256').update(b).digest('hex');
async function scan(dir){const a=[];for(const e of await fs.readdir(path.join(root,dir),{withFileTypes:true})){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())a.push(...await scan(n));else if(e.isFile())a.push(n);}return a.sort();}
const files=['src/main.js','src/ai.js','src/weapons.js','src/schools.js','src/characters.js',own,'package.json','package-lock.json',...await scan('dist')];
const manifest=async()=>Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),startedUTC=new Date().toISOString(),start=performance.now();
await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n');await fs.copyFile(path.join(root,own),path.join(out,'executed-tool.mjs'));
const settings={difficulty:'normal',pixel:false,blood:true,sound:false,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false},settingsBytes=JSON.stringify(settings);
const errors=[],compiled=[],entries=[],inputRequests=[],secrets=[],launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,4000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,pass=false;
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(15000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});return route.abort('blockedbyclient');}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});assert(!(r.status()>=300&&r.status()<400));const rel=new URL(url).pathname.slice(base.pathname.length);if(!rel||rel.startsWith('assets/')&&rel.endsWith('.js')){const body=await r.body(),name='dist/'+(rel||'index.html'),wanted=before[name],digest=sha(body);compiled.push({name,sha256:digest,bytes:body.length,match:!!wanted&&wanted.bytes===body.length&&wanted.sha256===digest});await route.fulfill({response:r,body});}else await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});});
 const wait=(fn,arg,timeout=45000)=>page.waitForFunction(fn,arg,{timeout:Math.max(100,Math.min(timeout,240000-(performance.now()-start)))});
 const read=()=>page.evaluate(()=>identityProbe.read());
 async function install(){await page.evaluate(()=>{const p=window.identityProbe={steps:0,native:[],ids:new WeakMap(),next:1};const id=o=>{if(!p.ids.has(o))p.ids.set(o,p.next++);return p.ids.get(o);};
 p.read=()=>({url:location.href,state:game.state,steps:p.steps,simTime:game.stats.simTime,fightT:game.player.fightT,objects:{player:id(game.player),enemy:id(game.enemy),world:id(game.world),ai:id(game.ai)},enemy:{name:game.enemy.name,weapon:game.enemy.weapon.id,school:game.ai.school.id,thrusts:game.ai.school.tech.filter(t=>t.kind==='thrust').map(t=>t.name),measure:{...game.ai.M},blood:game.enemy.blood,wounds:game.enemy.wounds.length},player:{weapon:game.player.weapon.id,gun:!!game.player.weapon.gun,edged:game.player.weapon.edged,blood:game.player.blood,wounds:game.player.wounds.length},policies:{v2:game.player.swordsmanshipModel??'legacy',arm:game.player.onehandArmModel,stance:game.player.stanceMemoryModel,roll:game.player.rollTargetModel,cut:game.combat.cutReactionModel,gravity:game.world.gravity.y,startHold:game.config.ARENA.startHold,defaultActive:game.swordsmanshipDefault.active},cards:{ids:[...game.draw.ids],stage:game.draw.stage,t:game.draw.t,pick:game.draw.pick,foeLabel:document.querySelector('#draw .wcard[data-i="2"]').getAttribute('aria-label'),foeName:document.querySelector('#draw .wcard[data-i="2"] .wname').textContent},input:{activeTouch:game.input.activeTouch,stick:[game.input.stickMove.x,game.input.stickMove.y],pending:[game.input.handDX,game.input.handDY]},saved:localStorage.getItem('gladiator-settings'),finite:[game.player,game.enemy].every(f=>[...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite))))});
 const cp=Object.getPrototypeOf(game.combat),original=cp.afterStep;cp.afterStep=function(...a){const ret=original.apply(this,a);if(this===game.combat)p.steps++;return ret;};
 for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<160)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.closest?.('button')?.id||e.target.id});},true);
 });}
 async function enter(row){await page.locator('#btnStart').tap();await wait(()=>game.state==='draw'&&game.draw.stage==='choose'&&game.draw.t>=.5);row.offer=await read();assert.equal(row.offer.cards.ids[2],'rubber_chicken');assert.equal(row.offer.cards.foeName,'고무 닭');await page.locator('#draw button[data-i="0"]').tap();await wait(()=>game.draw.stage==='reveal'&&game.draw.t>=1||game.draw.stage==='fly'||game.state==='fight');row.reveal=await read();if(row.reveal.cards.stage==='reveal')await page.locator('#draw button[data-i="0"]').tap();await wait(()=>game.state==='fight'&&game.player.fightT>0);row.started=await read();assert.equal(row.started.player.weapon,row.offer.cards.ids[0]);assert.equal(row.started.enemy.weapon,'rubber_chicken');assert.equal(row.started.enemy.name,'오소리 브란');assert(row.started.cards.foeLabel.startsWith('상대 무기: 고무 닭'));assert.equal(row.started.saved,settingsBytes);assert(row.started.finite);assert(row.started.policies.defaultActive);assert.equal(row.started.policies.gravity,-9.81);assert.equal(row.started.policies.startHold,2);assert.equal(row.started.policies.stance,'fresh');assert.equal(row.started.policies.roll,row.started.player.gun?'legacy':'bounded');assert.equal(row.started.policies.cut,row.started.player.edged&&!row.started.player.gun?'centerline':'legacy');const v2=!row.started.player.gun&&!['monohoshizao','lightsaber'].includes(row.started.player.weapon);assert.equal(row.started.policies.v2,v2?'unified':'legacy');if(v2)assert.equal(row.started.policies.arm,'manual');assert.equal(row.started.enemy.school,row.expectedSchool);assert.equal(row.started.enemy.thrusts.length,row.expectedSchool==='longsword'?5:0);console.log(JSON.stringify({event:'entered',query:row.query,round:row.round,school:row.started.enemy.school,simTime:row.started.simTime}));}
 async function send(type,touchPoints){inputRequests.push({type,touchPoints});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints});}
 async function nativeInput(row){const s=await read();await send('touchStart',[{x:675,y:240,id:1}]);await send('touchMove',[{x:650,y:200,id:1}]);row.handHeld=await read();assert.notEqual(row.handHeld.input.activeTouch,null);await wait(n=>identityProbe.steps>n,s.steps,10000);await send('touchEnd',[]);const b=await page.locator('#moveStick').boundingBox();assert(b);await send('touchStart',[{x:b.x+b.width/2,y:b.y+b.height/2,id:2}]);await send('touchMove',[{x:b.x+b.width/2,y:b.y+b.height/2-25,id:2}]);row.stickHeld=await read();assert(row.stickHeld.input.stick.some(x=>Math.abs(x)>.1));await send('touchEnd',[]);row.advanced=await read();assert(row.advanced.steps>s.steps);}
 for(const query of ['chicken','rubber_chicken']){
  const url=new URL(base);url.search=new URLSearchParams({foe:'bran',foeWeapon:query}).toString();await page.goto(url.href,{waitUntil:'load',timeout:30000});await wait(()=>window.game?.ai&&game?.combat);await install();cdp=await context.newCDPSession(page);
  const expectedSchool=query==='chicken'&&args.expect==='baseline'?'longsword':'rubber_chicken';
  for(let round=1;round<=(query==='chicken'?2:1);round++){
   const row={query,round,expectedSchool};entries.push(row);await enter(row);if(round===2){const previous=entries.at(-2).paused;for(const k of Object.keys(previous.objects))assert.notEqual(row.started.objects[k],previous.objects[k]);assert.equal(row.started.enemy.wounds,0);assert.equal(row.started.player.wounds,0);}
   await nativeInput(row);await page.locator('#btnPause').tap();await wait(()=>game.state==='paused');row.paused=await read();assert.equal(row.paused.input.activeTouch,null);assert.deepEqual(row.paused.input.stick,[0,0]);assert.equal(row.paused.enemy.school,expectedSchool);assert(row.paused.simTime<8);row.native=await page.evaluate(()=>identityProbe.native);assert(row.native.length>0&&row.native.every(e=>e.trusted&&e.kind==='touch'));await page.screenshot({path:path.join(out,`${query}-${round}.png`)});
  }
  await cdp.detach();cdp=null;
 }
 assert(compiled.some(x=>x.name==='dist/index.html')&&compiled.some(x=>x.name.startsWith('dist/assets/main-')));assert(compiled.every(x=>x.match));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;}
finally{
 if(cdp)await cdp.detach().catch(()=>{});if(context)await context.close();if(browser)await browser.close();const after=await manifest(),buildStable=files.filter(n=>n.startsWith('dist/')||n===own).every(n=>JSON.stringify(before[n])===JSON.stringify(after[n])),sourceStable=files.filter(n=>!n.startsWith('dist/')&&n!==own).every(n=>JSON.stringify(before[n])===JSON.stringify(after[n]));
 pass=pass&&buildStable&&errors.length===0&&performance.now()-start<240000;if(!pass)process.exitCode=1;const report={pass,expect:args.expect,head,startedUTC,completedUTC:new Date().toISOString(),wallMs:performance.now()-start,base:base.href,buildStable,sourceStable,settings,entries,compiled,errors,fatal,inputRequests,tlsVerification:true,proxyRetained:!local,limits:['Three short native rounds; randomized player cards, no RNG/pose/physics/AI/damage assignments.','School technique membership is not proof of actual thrust selection: blunt damage ratio 0/0 suppresses those candidates.','Observers only forward the original combat afterStep and record trusted events. No balance, natural damage or full combat claim.','Executed build bytes are matched to frozen dist manifest; concurrent source edits are recorded separately.']};await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');await fs.writeFile(path.join(out,'manifest-after.json'),JSON.stringify(after,null,2)+'\n');console.log(JSON.stringify({pass,buildStable,sourceStable,rounds:entries.length,wallMs:report.wallMs,fatal,out}));
}
