// One natural-injury episode, held pause/resume/new input and one minimal restart check.
// No replay equivalence, synthetic wounds, transform/AI assignments or severing search.
// PLAYWRIGHT_MODULE=... PLAYWRIGHT_BROWSERS_PATH=... node tools/browser/phase3_closure_mobile_20261007.mjs --out=<fresh-dir> [--base=<own-base/>]
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/phase3_closure_mobile_20261007.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/phase3-round3-20261007/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString();await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:false,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],responseTasks=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false;
const checks={}, flow={}, reusedEvidence={};
const previousRoot='/workspace/halfsword-handoff/phase3-round2-20261007/browser/public01';
const previousBytes=await fs.readFile(previousRoot+'/report.json');
const previous=JSON.parse(previousBytes),previousManifest=JSON.parse(await fs.readFile(previousRoot+'/manifest-before.json','utf8'));
assert(previous.pass&&previous.sourceStable&&previous.exposure.openedEvents.length);
for(const [name,value] of Object.entries(before))if(name.startsWith('src/')||name.startsWith('dist/assets/'))assert.deepEqual(value,previousManifest.files[name],'Prior visual evidence game source/compiled bytes differ: '+name);
Object.assign(reusedEvidence,{path:previousRoot+'/report.json',bytes:previousBytes.length,sha256:sha(previousBytes),gameSourceAndCompiledExact:true,scope:'Stored cut, attached marks, object rendering and visible blood only; injury interruption/restart is new work.'});
const takeShot=async(name)=>{const b=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));await page.screenshot({path:path.join(out,name+'.png')});const a=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));shots.push({file:name+'.png',before:b,after:a});};
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block',recordVideo:{dir:path.join(out,'video'),size:{width:844,height:390}}});context.setDefaultTimeout(60000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});const u=new URL(r.url());if(!confined(u.href)||!u.pathname.includes('/assets/')||!u.pathname.endsWith('.js'))return;responseTasks.push((async()=>{const b=await r.body(),n='dist/'+u.pathname.slice(base.pathname.length),expected=before[n];compiled.push({url:u.href,bytes:b.length,sha256:sha(b),match:!!expected&&b.length===expected.bytes&&sha(b)===expected.sha256});})().catch(e=>errors.push({kind:'asset',message:clean(e.message)})));});
 const verificationFiles=['index.html','feature-lab.html','development-plan.html','sounds.html',...(await fs.readdir(path.join(root,'dist/assets'))).filter(n=>n.endsWith('.js')).map(n=>'assets/'+n)];assert.equal(verificationFiles.length,8);
 for(const n of verificationFiles){const url=new URL(n,base);assert(confined(url.href));const r=await context.request.get(url.href,{maxRedirects:0,maxRetries:2});assert.equal(r.status(),200);const b=await r.body(),expected=before['dist/'+n];const row={name:n,bytes:b.length,sha256:sha(b),match:expected.bytes===b.length&&expected.sha256===sha(b)};fileChecks.push(row);assert(row.match,'Delivered bytes differ: '+n);}
 const url=new URL(base);url.search='weapon=longsword&foe=heinrich&foeWeapon=longsword';await page.goto(url.href,{waitUntil:'load'});await page.waitForFunction(()=>game?.player?.sword&&game?.combat&&game?.swordsmanshipDefault);await page.waitForLoadState('networkidle');
 await page.evaluate(()=>{
  const p=window.closureProbe={phase:'menu',applications:[],native:[],firstFighters:[],firstWorlds:[],firstAIs:[],steps:0,nonfinite:0,inputs:[],ai:{calls:0,freeAliveCalls:0},ids:new WeakMap(),nextId:1,seenFighters:new WeakSet(),seenWorlds:new WeakSet(),seenAIs:new WeakSet(),lastInputIds:new Set()};
  const id=o=>{if(!p.ids.has(o))p.ids.set(o,p.nextId++);return p.ids.get(o);};
  const role=f=>f===game.player?'player':f===game.enemy?'enemy':'other';
  const finite=f=>[...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite)));
  const state=f=>{const s=f.swordsmanshipState;return s?{version:s.version,phase:s.phase,owner:s.owner,seeded:s.seeded,goalTick:s.goalTick,idleS:s.idleS,generatedDX:s.generatedDX,generatedDY:s.generatedDY,returnVX:s.returnVX,returnVY:s.returnVY,lastBatchId:s.lastBatchId,lastMotionTimeS:s.lastMotionTimeS,input:s.input?{...s.input}:null,hasIntent:s.hasIntent,released:s.released,reversing:s.reversing,eligible:s.eligible,availability:s.availability,hand:s.hand.toArray(),aim:s.aim.toArray()}:null;};
  const health=f=>({id:id(f),role:role(f),weapon:f.weapon.id,name:f.name,alive:f.alive,armed:f.armed,state:f.state,fightT:f.fightT,blood:f.blood,bleed:f.bleed,consciousness:f.consciousness,pain:f.pain,daze:f.daze,limbs:{...f.limbs},wounds:f.wounds.map(w=>({part:w.part,type:w.type,severity:w.severity,bleed:w.bleed,local:w.local.toArray(),stump:!!w.stump,soak:w.soak?.uuid??null})),detachedParts:[...(f.detachedParts??[])],severedLimbs:(f.severedLimbs??[]).length,cloth:{...f.cloth},helmetIntegrity:f.helmetIntegrity,plate:{...f.plate},hand:f.handOffset.toArray(),held:!!f.handHeld,active:!!f.inputActive,thrusts:f.skill.thrusts,tap:f.skill.tap?{t:f.skill.tap.t,down:f.skill.tap.down}:null,finishAmt:f.finish.amt,controller:state(f),history:{prevAim:f.prevAim?.toArray()??null,wristBrake:!!f.wristBrake,hitCooldowns:[...f.hitCooldowns],gaitStarted:!!f.gait.started,friction:Object.fromEntries(Object.entries(f.gait.legs).map(([k,l])=>[k,l.Nf??null]))},finite:finite(f)});
  p.read=()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame,state:game.state,phase:p.phase,objects:{player:id(game.player),enemy:id(game.enemy),world:id(game.world),combat:id(game.combat),ai:id(game.ai),controller:id(game.player.swordsmanshipState)},player:health(game.player),enemy:health(game.enemy),policies:{default:game.swordsmanshipDefault.active,v2:game.player.swordsmanshipModel,skill:game.player.skill.level,autoGuard:game.player.skill.autoGuard,arm:game.player.onehandArmModel,stance:game.player.stanceMemoryModel,roll:game.player.rollTargetModel,cut:game.combat.cutReactionModel,cutPlayer:game.combat.cutReactionFighter===game.player,limb:game.config.COMBAT.limbSeverTrial,finish:game.combat.finishRuleModel,gravity:game.world.gravity.y,enemyController:game.enemy.swordsmanshipModel??'legacy',enemyArm:game.enemy.onehandArmModel,aiLevel:game.ai.levelName,persona:JSON.parse(JSON.stringify(game.ai.persona))},input:{enabled:game.input.enabled,activeTouch:game.input.activeTouch,pending:{x:game.input.handDX,y:game.input.handDY},taps:game.input.taps,press:game.input.press?{id:game.input.press.id}:null,keys:[...game.input.keys],stick:{...game.input.stickMove}},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings')});
  const fp=Object.getPrototypeOf(game.player),apply=fp.applyWound,step=fp.step;
  fp.applyWound=function(h){const before=health(this),ret=apply.call(this,h),after=health(this);p.applications.push({timeS:game.stats.simTime,phase:p.phase,victim:role(this),part:h.part,result:Object.fromEntries(['type','zone','energy','severity','pass','finish','plate','helmet'].map(k=>[k,h[k]??null])),before,after});return ret;};
  fp.step=function(...args){if((this===game.player||this===game.enemy)&&!p.seenFighters.has(this)){p.seenFighters.add(this);p.firstFighters.push({role:role(this),snapshot:p.read()});}return step.apply(this,args);};
  const wp=Object.getPrototypeOf(game.world),ws=wp.step;wp.step=function(...args){if(this===game.world&&!p.seenWorlds.has(this)){p.seenWorlds.add(this);p.firstWorlds.push(p.read());}return ws.apply(this,args);};
  const ap=Object.getPrototypeOf(game.ai),au=ap.update;ap.update=function(...args){if(this===game.ai){if(!p.seenAIs.has(this)){p.seenAIs.add(this);p.firstAIs.push(p.read());}p.ai.calls++;if(this.me.alive&&!this.me.feetHeld)p.ai.freeAliveCalls++;}return au.apply(this,args);};
  const cp=Object.getPrototypeOf(game.combat),cs=cp.afterStep;cp.afterStep=function(...args){const ret=cs.apply(this,args);if(this===game.combat){p.steps++;if(!finite(game.player)||!finite(game.enemy))p.nonfinite++;const s=game.player.swordsmanshipState;if(s.input?.active&&Math.hypot(s.input.dx,s.input.dy)>1e-5&&p.phase!=='approach-and-cuts'){const key=id(game.player)+':'+s.lastBatchId;if(!p.lastInputIds.has(key)){p.lastInputIds.add(key);p.inputs.push(p.read());}}}return ret;};
  for(const type of['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<2500)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.id,timeS:game.stats.simTime,phase:p.phase,x:e.clientX,y:e.clientY});},true);
 });
 const snap=()=>page.evaluate(()=>closureProbe.read());
 const cleanInput=v=>{assert.deepEqual(v.input.pending,{x:0,y:0});assert.equal(v.input.activeTouch,null);assert.equal(v.input.taps,0);assert.equal(v.input.press,null);assert.deepEqual(v.input.keys,[]);assert.deepEqual(v.input.stick,{x:0,y:0});};
 const policy=v=>{assert.deepEqual(v.settings,seeds);assert.equal(v.saved,settingsBytes);const c=v.policies;assert(c.default&&c.v2==='unified'&&c.skill===0&&!c.autoGuard&&c.arm==='manual'&&c.stance==='fresh'&&c.roll==='bounded'&&c.cut==='centerline'&&c.cutPlayer&&c.limb&&c.finish==='legacy'&&c.gravity===-9.81&&c.enemyController==='legacy'&&c.enemyArm==='legacy'&&c.aiLevel==='normal');assert.deepEqual(c.persona,flow.menu?.policies.persona??c.persona);assert(v.player.finite&&v.enemy.finite);};
 const freshHealth=f=>{assert(f.alive&&f.armed);assert.equal(f.blood,1);assert.equal(f.bleed,0);assert.equal(f.consciousness,1);assert.equal(f.pain,0);assert.equal(f.daze,0);assert.deepEqual(f.wounds,[]);assert.deepEqual(f.limbs,{armS:1,armO:1,legF:1,legB:1});assert.deepEqual(f.detachedParts,[]);assert.equal(f.severedLimbs,0);assert.deepEqual(f.cloth,{});assert.equal(f.helmetIntegrity,1);assert(Object.values(f.plate).every(v=>v===1));assert.equal(f.tap,null);assert.equal(f.thrusts,0);assert.equal(f.finishAmt,0);assert.deepEqual(f.history.hitCooldowns,[]);};
 flow.menu=await snap();policy(flow.menu);cleanInput(flow.menu);await page.locator('#btnStart').tap();await page.waitForFunction(()=>game.state==='fight'&&closureProbe.firstWorlds.length===1);flow.started=await snap();policy(flow.started);cdp=await context.newCDPSession(page);
 const pad=await page.locator('#moveStick').boundingBox();assert(pad);const stick={x:pad.x+pad.width/2,y:pad.y+pad.height/2,id:1},hand={x:650,y:210,id:2};
 async function send(type,points){inputRequests.push({type,points:points.map(p=>({...p}))});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
 const brief=()=>page.evaluate(()=>({t:game.stats.simTime,state:game.state,viable:game.player.alive&&game.player.armed&&game.enemy.alive,gap:Math.hypot(game.player.pelvisPos.x-game.enemy.pelvisPos.x,game.player.pelvisPos.z-game.enemy.pelvisPos.z),cut:closureProbe.applications.some(e=>e.victim==='player'&&e.after.wounds.length>e.before.wounds.length&&e.result.type==='cut'),injury:closureProbe.applications.some(e=>e.victim==='player'&&(e.after.wounds.length>e.before.wounds.length||e.after.pain!==e.before.pain||e.after.consciousness!==e.before.consciousness||JSON.stringify(e.after.limbs)!==JSON.stringify(e.before.limbs)))}));
 async function advance(delta){const b=await brief();await page.waitForFunction(t=>game.stats.simTime>=t||game.state!=='fight',Math.min(24,b.t+delta),{timeout:45000});return brief();}
 await page.evaluate(()=>{closureProbe.phase='approach-and-cuts';});await send('touchStart',[stick]);let status=await brief(),cycles=0;
 while(status.t<23&&status.state==='fight'&&status.viable&&cycles<5){
  stick.y=pad.y+pad.height/2-(status.gap>1.35?36:status.gap<.85?-24:0);await send('touchMove',[stick]);hand.x=670;hand.y=240;await send('touchStart',[stick,hand]);
  for(let n=1;n<=5;n++){hand.x=670-18*n;hand.y=240-22*n;await send('touchMove',[stick,hand]);status=await advance(.09);if(status.t>=23||status.state!=='fight'||!status.viable)break;}
  if(status.state==='fight'&&status.viable&&status.t<23){status=await advance(.15);for(let n=1;n<=5;n++){hand.x=580+23*n;hand.y=130+25*n;await send('touchMove',[stick,hand]);status=await advance(.07);if(status.t>=23||status.state!=='fight'||!status.viable)break;}}
  await send('touchEnd',[stick]);cycles++;status=await brief();if(status.cut)break;if(status.state==='fight'&&status.viable&&status.t<23)status=await advance(.18);
 }
 await send('touchEnd',[]);flow.exposure=await snap();flow.cycles=cycles;flow.exposureStatus=status;policy(flow.exposure);checks.naturalInjury=status.injury?'exposed': 'unexposed';checks.openedCut=status.cut?'exposed':'unexposed';
 if(status.state==='fight'&&status.viable){
  async function heldPause(label){await page.evaluate(x=>{closureProbe.phase=x;},label);const h={x:620,y:220,id:2};await send('touchStart',[h]);h.y=190;await send('touchMove',[h]);await page.waitForFunction(()=>game.player.handHeld&&game.input.activeTouch!==null);const held=await snap();const box=await page.locator('#btnPause').boundingBox();assert(box);const button={x:box.x+box.width/2,y:box.y+box.height/2,id:3};await send('touchStart',[h,button]);await send('touchEnd',[h]);await page.waitForFunction(()=>game.state==='paused');const paused=await snap();cleanInput(paused);assert.equal(paused.input.enabled,false);await send('touchEnd',[]);await page.waitForTimeout(180);const later=await snap();assert.equal(later.timeS,paused.timeS);assert.deepEqual(later.player,paused.player);assert.deepEqual(later.enemy,paused.enemy);assert.deepEqual(later.objects,paused.objects);policy(later);return{held,paused,later};}
  async function newInput(label){await page.evaluate(x=>{closureProbe.phase=x;},label);const before=await snap(),count=await page.evaluate(()=>closureProbe.inputs.length),h={x:620,y:220,id:2};cleanInput(before);await send('touchStart',[h]);for(let n=1;n<=3;n++){h.x=620+12*n;h.y=220-10*n;await send('touchMove',[h]);await page.waitForTimeout(45);}await page.waitForFunction(n=>closureProbe.inputs.length>n,count);const consumed=await page.evaluate(n=>closureProbe.inputs.slice(n),count);assert(consumed.some(v=>v.player.held&&v.player.controller.input.active&&Math.hypot(v.player.controller.input.dx,v.player.controller.input.dy)>1e-5));for(const v of consumed){assert.notEqual(v.player.controller.owner,'return');assert.equal(v.player.controller.generatedDX,0);assert.equal(v.player.controller.generatedDY,0);policy(v);}await send('touchEnd',[]);await page.waitForFunction(()=>game.input.activeTouch===null&&!game.player.handHeld);const after=await snap();assert.equal(after.player.thrusts,before.player.thrusts,'Drag became tap');policy(after);return{before,consumed,after};}
  flow.injuredPause=await heldPause('injured-held-pause');await takeShot('injured-paused');await page.locator('#btnResume').tap();await page.waitForFunction(()=>game.state==='fight');flow.resumed=await snap();cleanInput(flow.resumed);assert.equal(flow.resumed.input.enabled,true);assert.deepEqual(flow.resumed.objects,flow.injuredPause.paused.objects);assert(flow.resumed.player.wounds.length>=flow.injuredPause.paused.player.wounds.length);policy(flow.resumed);flow.injuredNewInput=await newInput('after-injury-input');checks.pauseResumeAndNewInput=status.injury?'injured_exposed_pass':'uninjured_only_pass';
  flow.beforeRestart=await heldPause('restart-held-pause');await page.locator('#btnStart').tap();await page.waitForFunction(()=>game.state==='fight'&&closureProbe.firstWorlds.length===2);flow.restarted=await snap();policy(flow.restarted);for(const key of Object.keys(flow.beforeRestart.paused.objects))assert.notEqual(flow.restarted.objects[key],flow.beforeRestart.paused.objects[key],'Old object retained: '+key);
  flow.restartBoundaries=await page.evaluate(()=>({fighters:closureProbe.firstFighters.slice(2),world:closureProbe.firstWorlds[1],ai:closureProbe.firstAIs[1]}));const boundary=flow.restartBoundaries.fighters.find(v=>v.role==='player').snapshot;policy(boundary);freshHealth(boundary.player);freshHealth(boundary.enemy);assert.equal(boundary.player.fightT,0);assert.deepEqual(boundary.player.history,flow.menu.player.history);for(const key of['goalTick','hasIntent','lastMotionTimeS','returnVX','returnVY','generatedDX','generatedDY','released','reversing'])assert.deepEqual(boundary.player.controller[key],flow.menu.player.controller[key],key+' retained pre-restart history');assert(!boundary.player.controller.input?.active);cleanInput(boundary);checks.restartFreshState='exposed_pass';
  flow.restartNewInput=await newInput('restart-new-input');await page.locator('#btnPause').tap();await page.waitForFunction(()=>game.state==='paused');flow.final=await snap();cleanInput(flow.final);policy(flow.final);assert(flow.final.player.fightT<2,'Restart ran beyond its minimal input window');checks.restartNewInput='exposed_pass';await takeShot('restart-paused');
 }else{checks.pauseResumeAndNewInput='unexposed_terminal_or_unarmed';checks.restartFreshState='unrun';checks.restartNewInput='unrun';flow.final=await snap();await takeShot('terminal');}
 episode=await page.evaluate(()=>{const p=closureProbe;return{applications:p.applications,native:p.native,firstFighters:p.firstFighters,firstWorlds:p.firstWorlds,firstAIs:p.firstAIs,inputs:p.inputs,ai:p.ai,steps:p.steps,nonfinite:p.nonfinite,final:p.read()};});assert(episode.final.timeS<=30,'Cumulative episode plus minimal restart exceeds 30 simulation seconds');assert.equal(episode.nonfinite,0);assert(episode.ai.freeAliveCalls>0);assert(episode.native.every(e=>e.trusted&&e.kind==='touch'));assert.equal(episode.firstWorlds.length,checks.restartFreshState==='exposed_pass'?2:1);assert.deepEqual(episode.final.settings,seeds);assert.equal(episode.final.saved,settingsBytes);await Promise.all(responseTasks);assert(compiled.length&&compiled.every(x=>x.match));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page){await takeShot('failure');episode=await page.evaluate(()=>{const p=window.closureProbe;return p?{final:p.read(),applications:p.applications,native:p.native,firstFighters:p.firstFighters,firstWorlds:p.firstWorlds,firstAIs:p.firstAIs,inputs:p.inputs,ai:p.ai,steps:p.steps,nonfinite:p.nonfinite}:null;});}}catch{}}
finally{
 if(cdp)await cdp.detach();await Promise.all(responseTasks);if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();const sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable;if(!pass)process.exitCode=1;
 const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),base:base.href,scenario:'One ordinary longsword/Heinrich episode plus minimal restarted input; original normal AI and legacy finish',maxCumulativeSimSeconds:30,settings:seeds,checks,reusedEvidence,fileChecks,compiled,shots,errors,fatal,flow,episode,inputRequests,limitations:['A natural cut is preferred; an actually applied blunt health change can expose injury interruption. Missing exposure is not a passed injury check.','Private bounded-roll history is a WeakMap keyed by Fighter; new Fighter identity and source contract establish isolation, not a direct map read.','Main cumulative stats.simTime/input batch IDs persist across restart; per-Fighter clock and controller intent are checked for reset.','Round2 wound rendering is reused by identical game source/compiled hashes. No renderer sampler, synthetic injury, position or AI injection.','No physical-phone performance, blood-OFF matched replay, severing search or exact headless-tape reenactment claim.'],tlsVerification:true,proxyRetained:!local,redirectsFollowed:false};
 await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,checks,applications:episode?.applications?.length,simTime:episode?.final?.timeS,fatal,out}));
}
