// Three short ordinary rounds in one context; passive resource and CPU-submission profiling.
// No replay equivalence, synthetic wounds, transform/AI assignments or severing search.
// PLAYWRIGHT_MODULE=... PLAYWRIGHT_BROWSERS_PATH=... node tools/browser/phase4_repeat_20261007.mjs --out=<fresh-dir> [--base=<own-base/>]
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/phase4_repeat_20261007.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/phase4-20261007/repeat';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString();await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:false,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],responseTasks=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false;
const checkpoints=[], rounds=[];
const takeShot=async(name)=>{const b=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));await page.screenshot({path:path.join(out,name+'.png')});const a=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));shots.push({file:name+'.png',before:b,after:a});};
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(60000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});const u=new URL(r.url());if(!confined(u.href)||!u.pathname.includes('/assets/')||!u.pathname.endsWith('.js'))return;responseTasks.push((async()=>{const b=await r.body(),n='dist/'+u.pathname.slice(base.pathname.length),expected=before[n];compiled.push({url:u.href,bytes:b.length,sha256:sha(b),match:!!expected&&b.length===expected.bytes&&sha(b)===expected.sha256});})().catch(e=>errors.push({kind:'asset',message:clean(e.message)})));});
 const verificationFiles=['index.html','feature-lab.html','development-plan.html','sounds.html',...(await fs.readdir(path.join(root,'dist/assets'))).filter(n=>n.endsWith('.js')).map(n=>'assets/'+n)];assert.equal(verificationFiles.length,8);
 for(const n of verificationFiles){const url=new URL(n,base);assert(confined(url.href));const r=await context.request.get(url.href,{maxRedirects:0,maxRetries:2});assert.equal(r.status(),200);const b=await r.body(),expected=before['dist/'+n];const row={name:n,bytes:b.length,sha256:sha(b),match:expected.bytes===b.length&&expected.sha256===sha(b)};fileChecks.push(row);assert(row.match,'Delivered bytes differ: '+n);}
 const url=new URL(base);url.search='weapon=longsword&foe=heinrich&foeWeapon=longsword&stage=poseidon';await page.goto(url.href,{waitUntil:'load'});await page.waitForFunction(()=>game?.player?.sword&&game?.combat&&game?.swordsmanshipDefault);await page.waitForLoadState('networkidle');
 await page.evaluate(()=>{
  const p=window.repeatProbe={round:0,frames:[],events:[],native:[],nonfinite:0,steps:0,aiCalls:0,freeAliveAICalls:0,renderCalls:0,renderer:null,acc:{ai:0,fighter:0,world:0,combat:0,steps:0},worlds:new WeakSet(),objects:new WeakMap(),nextId:1};
  const id=o=>{if(!p.objects.has(o))p.objects.set(o,p.nextId++);return p.objects.get(o);};
  const finite=f=>[...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite)));
  const health=f=>({id:id(f),weapon:f.weapon.id,name:f.name,state:f.state,alive:f.alive,armed:f.armed,fightT:f.fightT,blood:f.blood,bleed:f.bleed,pain:f.pain,consciousness:f.consciousness,wounds:f.wounds.length,detached:(f.detachedParts?.size??0)});
  p.read=()=>({timeS:game.stats.simTime,state:game.state,round:p.round,stage:{...game.stage},objects:{player:id(game.player),enemy:id(game.enemy),world:id(game.world),combat:id(game.combat),ai:id(game.ai),controller:id(game.player.swordsmanshipState)},player:health(game.player),enemy:health(game.enemy),policies:{default:game.swordsmanshipDefault.active,v2:game.player.swordsmanshipModel,skill:game.player.skill.level,autoGuard:game.player.skill.autoGuard,arm:game.player.onehandArmModel,stance:game.player.stanceMemoryModel,roll:game.player.rollTargetModel,cut:game.combat.cutReactionModel,cutPlayer:game.combat.cutReactionFighter===game.player,limb:game.config.COMBAT.limbSeverTrial,finish:game.combat.finishRuleModel,gravity:game.world.gravity.y,enemyController:game.enemy.swordsmanshipModel??'legacy',enemyArm:game.enemy.onehandArmModel,aiLevel:game.ai.levelName},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),input:{enabled:game.input.enabled,activeTouch:game.input.activeTouch,pending:{x:game.input.handDX,y:game.input.handDY},press:game.input.press?{id:game.input.press.id}:null,taps:game.input.taps,stick:{...game.input.stickMove}},renderInfo:game.renderInfo(),cumulativeHits:game.stats.hits.length,cumulativeClashes:game.stats.clashes,canvas:{width:game.input.canvas.width,height:game.input.canvas.height,clientWidth:game.input.canvas.clientWidth,clientHeight:game.input.canvas.clientHeight},debris:game.debris.count()});
  p.resources=()=>{const scene=game.player.scene,geometries=new Map(),textures=new Map(),materials=new Map(),types={},decals={};let objects=0,visibleObjects=0,meshes=0;
   const rememberTexture=t=>{if(t?.isTexture)textures.set(t.uuid,{uuid:t.uuid,type:t.constructor.name});};
   scene.traverse(o=>{objects++;if(o.visible)visibleObjects++;types[o.type]=(types[o.type]||0)+1;if(o.isMesh)meshes++;if(o.geometry)geometries.set(o.geometry.uuid,{uuid:o.geometry.uuid,type:o.geometry.type});for(const m of(Array.isArray(o.material)?o.material:o.material?[o.material]:[])){materials.set(m.uuid,{uuid:m.uuid,type:m.type});for(const v of Object.values(m))rememberTexture(v);for(const u of Object.values(m.uniforms??{})){if(Array.isArray(u.value))u.value.forEach(rememberTexture);else rememberTexture(u.value);}}if(o.userData?.kind&&o.userData?.mesh)decals[o.userData.kind]=(decals[o.userData.kind]||0)+1;});
   return{...p.read(),scene:{objects,visibleObjects,meshes,types,decals,geometries:[...geometries.values()],materials:[...materials.values()],textures:[...textures.values()]},programs:p.renderer?.info.programs.map(v=>({id:v.id,name:v.name??null,usedTimes:v.usedTimes??null})),particles:scene.children.filter(o=>o.isInstancedMesh&&o.geometry?.type==='BoxGeometry'&&o.instanceMatrix?.count===500&&o.frustumCulled===false).map(o=>({uuid:o.uuid,count:o.count})),dom:{allElements:document.querySelectorAll('*').length,canvas:document.querySelectorAll('canvas').length},instrumentation:{renderCalls:p.renderCalls,physicsSteps:p.steps,aiCalls:p.aiCalls,freeAliveAICalls:p.freeAliveAICalls}};};
  const scene=game.player.scene,sceneBefore=scene.onBeforeRender;
  scene.onBeforeRender=function(renderer,...args){const result=sceneBefore.call(this,renderer,...args);p.renderer=renderer;scene.onBeforeRender=sceneBefore;return result;};
  const fp=Object.getPrototypeOf(game.player),apply=fp.applyWound;fp.applyWound=function(h){const before=health(this),ret=apply.call(this,h),after=health(this);p.events.push({round:p.round,timeS:game.stats.simTime,victim:this===game.player?'player':'enemy',part:h.part,result:Object.fromEntries(['type','zone','energy','severity','plate','helmet','pass','finish'].map(k=>[k,h[k]??null])),before,after});return ret;};
  function profile(proto,name,key,after){const original=proto[name];proto[name]=function(...args){const t=performance.now();let result;try{result=original.apply(this,args);}finally{p.acc[key]+=performance.now()-t;}after?.call(this);return result;};}
  profile(Object.getPrototypeOf(game.ai),'update','ai',function(){if(this===game.ai){p.aiCalls++;if(this.me.alive&&!this.me.feetHeld)p.freeAliveAICalls++;}});
  profile(fp,'step','fighter');
  profile(Object.getPrototypeOf(game.world),'step','world',function(){if(this===game.world){p.steps++;p.acc.steps++;}});
  profile(Object.getPrototypeOf(game.combat),'afterStep','combat',function(){if(!finite(game.player)||!finite(game.enemy))p.nonfinite++;});
  for(const type of['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<2000)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.id,round:p.round,timeS:game.stats.simTime,x:e.clientX,y:e.clientY});},true);
 });
 await page.waitForFunction(()=>repeatProbe.renderer);await page.evaluate(()=>{
  const p=repeatProbe,renderer=p.renderer,original=renderer.render;
  renderer.render=function(...args){const t=performance.now(),frameGapMs=p.lastRenderStart===undefined?null:t-p.lastRenderStart;p.lastRenderStart=t;let result;try{result=original.apply(this,args);}finally{const renderMs=performance.now()-t;p.renderCalls++;p.frames.push({round:p.round,state:game.state,timeS:game.stats.simTime,fightT:game.player.fightT,frame:this.info.render.frame,frameGapMs,aiMs:p.acc.ai,fighterMs:p.acc.fighter,worldMs:p.acc.world,combatMs:p.acc.combat,physicsSteps:p.acc.steps,renderMs});p.acc={ai:0,fighter:0,world:0,combat:0,steps:0};}return result;};
  p.instanceRenderWrapped=Object.hasOwn(renderer,'render')&&renderer.render!==original;
 });await page.waitForFunction(()=>repeatProbe.instanceRenderWrapped&&repeatProbe.renderCalls>=2);
 cdp=await context.newCDPSession(page);await cdp.send('Performance.enable');
 const read=()=>page.evaluate(()=>repeatProbe.read());
 const policy=v=>{assert.deepEqual(v.settings,seeds);assert.equal(v.saved,settingsBytes);const c=v.policies;assert(c.default&&c.v2==='unified'&&c.skill===0&&!c.autoGuard&&c.arm==='manual'&&c.stance==='fresh'&&c.roll==='bounded'&&c.cut==='centerline'&&c.cutPlayer&&c.limb&&c.finish==='legacy'&&c.gravity===-9.81&&c.enemyController==='legacy'&&c.enemyArm==='legacy'&&c.aiLevel==='normal');assert.equal(v.player.weapon,'longsword');assert.equal(v.enemy.weapon,'longsword');assert.equal(v.enemy.name,'하인리히 도른');assert.equal(v.stage.id,'poseidon');};
 async function checkpoint(label){const value=await page.evaluate(()=>repeatProbe.resources());policy(value);const dom=await cdp.send('Memory.getDOMCounters'),heap=await cdp.send('Runtime.getHeapUsage'),metrics=await cdp.send('Performance.getMetrics');const select=new Set(['Documents','Frames','JSEventListeners','Nodes','JSHeapUsedSize','JSHeapTotalSize','TaskDuration','ScriptDuration','LayoutDuration','RecalcStyleDuration','LayoutCount','RecalcStyleCount']);const row={label,...value,cdp:{dom,heap,metrics:Object.fromEntries(metrics.metrics.filter(v=>select.has(v.name)).map(v=>[v.name,v.value]))}};checkpoints.push(row);console.log(JSON.stringify({checkpoint:label,round:value.round,timeS:value.timeS,geometries:value.renderInfo.geometries,textures:value.renderInfo.textures,programs:value.renderInfo.programs,programUsedTimes:value.programs.reduce((s,v)=>s+(v.usedTimes??0),0),sceneObjects:value.scene.objects,sceneGeometries:value.scene.geometries.length,sceneMaterials:value.scene.materials.length,dom,heapUsed:heap.usedSize}));return row;}
 await checkpoint('menu-instrumented');
 async function send(type,points){inputRequests.push({type,points:points.map(p=>({...p}))});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
 const brief=()=>page.evaluate(()=>({timeS:game.stats.simTime,fightT:game.player.fightT,state:game.state,alive:game.player.alive,armed:game.player.armed,foeAlive:game.enemy.alive,gap:Math.hypot(game.player.pelvisPos.x-game.enemy.pelvisPos.x,game.player.pelvisPos.z-game.enemy.pelvisPos.z)}));
 async function advance(delta){const b=await brief();await page.waitForFunction(t=>game.player.fightT>=t||game.state!=='fight',Math.min(6.1,b.fightT+delta),{timeout:45000});return brief();}
 for(let round=1;round<=3;round++){
  await page.evaluate(n=>{repeatProbe.round=n;repeatProbe.acc={ai:0,fighter:0,world:0,combat:0,steps:0};},round);
  const row={round,startClickUTC:new Date().toISOString()};rounds.push(row);const startWall=performance.now();await page.locator('#btnStart').tap();await page.waitForFunction(()=>game.state==='fight'&&game.player.fightT>0);row.startWallMs=performance.now()-startWall;row.start=await checkpoint('round-'+round+'-start');
  if(round>1)for(const key of Object.keys(row.start.objects))assert.notEqual(row.start.objects[key],rounds[round-2].end.objects[key]);
  const pad=await page.locator('#moveStick').boundingBox();assert(pad);const stick={x:pad.x+pad.width/2,y:pad.y+pad.height/2,id:1},hand={x:670,y:240,id:2};await send('touchStart',[stick]);let status=await brief(),cycles=0;
  while(status.fightT<6.1&&status.state==='fight'&&cycles<8){
   stick.y=pad.y+pad.height/2-(status.gap>1.35?36:status.gap<.85?-24:0);await send('touchMove',[stick]);hand.x=670;hand.y=240;await send('touchStart',[stick,hand]);
   for(let n=1;n<=5;n++){hand.x=670-18*n;hand.y=240-22*n;await send('touchMove',[stick,hand]);status=await advance(.09);if(status.fightT>=6.1||status.state!=='fight')break;}
   if(status.fightT<6.1&&status.state==='fight'){status=await advance(.15);for(let n=1;n<=5;n++){hand.x=580+23*n;hand.y=130+25*n;await send('touchMove',[stick,hand]);status=await advance(.07);if(status.fightT>=6.1||status.state!=='fight')break;}}
   await send('touchEnd',[stick]);cycles++;status=await brief();if(status.fightT<6.1&&status.state==='fight')status=await advance(.18);
  }
  await send('touchEnd',[]);status=await brief();if(status.state==='fight'){await page.locator('#btnPause').tap();await page.waitForFunction(()=>game.state==='paused');}else row.terminalBeforePause=true;
  row.cycles=cycles;row.end=await checkpoint('round-'+round+'-paused');assert(row.end.player.fightT<=8.2,'Short round exceeded eight simulation seconds');assert(row.end.player.fightT>=4||row.terminalBeforePause,'Round ended before the intended observation window');
  assert.equal(row.end.input.activeTouch,null);assert.deepEqual(row.end.input.pending,{x:0,y:0});assert.deepEqual(row.end.input.stick,{x:0,y:0});await takeShot('round-'+round+'-paused');await page.waitForTimeout(200);row.settled=await checkpoint('round-'+round+'-paused-settled');assert.equal(row.settled.timeS,row.end.timeS);
  row.events=await page.evaluate(n=>repeatProbe.events.filter(v=>v.round===n),round);row.pass=true;
 }
 episode=await page.evaluate(()=>({final:repeatProbe.read(),frames:repeatProbe.frames,events:repeatProbe.events,native:repeatProbe.native,nonfinite:repeatProbe.nonfinite,steps:repeatProbe.steps,aiCalls:repeatProbe.aiCalls,freeAliveAICalls:repeatProbe.freeAliveAICalls,renderCalls:repeatProbe.renderCalls,instanceRenderWrapped:repeatProbe.instanceRenderWrapped}));assert(episode.instanceRenderWrapped&&episode.renderCalls>0);assert.equal(episode.nonfinite,0);assert(episode.freeAliveAICalls>0);assert(episode.native.every(v=>v.trusted&&v.kind==='touch'));assert.equal(episode.native.filter(v=>v.type==='pointerdown'&&v.target==='btnStart').length,3);assert.equal(episode.native.filter(v=>v.type==='pointerdown'&&v.target==='btnPause').length,3-rounds.filter(v=>v.terminalBeforePause).length);assert.deepEqual(episode.final.settings,seeds);assert.equal(episode.final.saved,settingsBytes);await Promise.all(responseTasks);assert(compiled.length&&compiled.every(v=>v.match));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page){await takeShot('failure');episode=await page.evaluate(()=>{const p=window.repeatProbe;return p?{final:p.read(),frames:p.frames,events:p.events,native:p.native,nonfinite:p.nonfinite,steps:p.steps,aiCalls:p.aiCalls,freeAliveAICalls:p.freeAliveAICalls,renderCalls:p.renderCalls,instanceRenderWrapped:p.instanceRenderWrapped}:null;});}}catch{}}
finally{
 if(cdp)await cdp.detach();await Promise.all(responseTasks);if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();const sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable;if(!pass)process.exitCode=1;
 const summary=values=>{const a=values.filter(Number.isFinite).sort((x,y)=>x-y);return{count:a.length,sum:a.reduce((s,x)=>s+x,0),mean:a.length?a.reduce((s,x)=>s+x,0)/a.length:null,median:a.length?a[Math.floor((a.length-1)*.5)]:null,p95:a.length?a[Math.floor((a.length-1)*.95)]:null,max:a.at(-1)??null};};
 const profiles=rounds.map(r=>{const frames=(episode?.frames??[]).filter(v=>v.round===r.round&&v.state==='fight');return{round:r.round,frames:frames.length,aiMs:summary(frames.map(v=>v.aiMs)),fighterMs:summary(frames.map(v=>v.fighterMs)),worldMs:summary(frames.map(v=>v.worldMs)),combatMs:summary(frames.map(v=>v.combatMs)),corePhysicsMs:summary(frames.map(v=>v.aiMs+v.fighterMs+v.worldMs+v.combatMs)),renderSubmissionMs:summary(frames.map(v=>v.renderMs)),frameGapMs:summary(frames.map(v=>v.frameGapMs)),physicsSteps:frames.reduce((s,v)=>s+v.physicsSteps,0)};});
 const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),base:base.href,scenario:'Three ~6-second ordinary longsword/Heinrich rounds in one context; fixed ordinary poseidon stage; original normal AI; trusted pause/restart',settings:seeds,rounds,checkpoints,profiles,episode,fileChecks,compiled,shots,inputRequests,errors,fatal,measurementNotes:['renderer.info.memory counts geometry/texture objects, not GPU bytes; program usedTimes counts program references, not byte memory.','Scene inventory includes attached objects/materials/textures, distinct from renderer allocated-resource counters and detached JavaScript objects.','CDP Memory.getDOMCounters/Runtime.getHeapUsage are direct read-only measurements. No forced GC; normal GC timing and caches can change heap/node/listener counts.','Physics sums AI.update, both Fighter.step, world.step and Combat.afterStep synchronous wall durations. It excludes frame input, camera/effects and observer bookkeeping outside timed calls.','The actual renderer instance render method is wrapped after discovery through Scene.onBeforeRender; original return/throw semantics are retained and invocation count is checked.','renderMs is synchronous CPU submission/blocking time including driver waits, not isolated GPU duration. Frame gaps and all cloud timings are not physical-phone FPS.','Same normal controls and stage do not make randomized AI/contact outcomes identical; three rounds can show a repeated-growth signal, not prove unbounded growth.','No injury/position/velocity/AI/physics-state injection, no giant physical snapshots or video recording.'],tlsVerification:true,proxyRetained:!local,redirectsFollowed:false};
 await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,rounds:rounds.length,steps:episode?.steps,renderCalls:episode?.renderCalls,fatal,out}));
}
