// One bounded ordinary browser episode; passive observations plus trusted native controls.
// No replay equivalence, synthetic wounds, transform/AI assignments or severing search.
// PLAYWRIGHT_MODULE=... PLAYWRIGHT_BROWSERS_PATH=... node tools/browser/phase3_damage_visual_20261007.mjs --out=<fresh-dir> [--base=<own-base/>]
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/phase3_damage_visual_20261007.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/phase3-round2-20261007/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString();await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:false,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],responseTasks=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false;
const takeShot=async(name)=>{const b=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));await page.screenshot({path:path.join(out,name+'.png')});const a=await page.evaluate(()=>({timeS:game.stats.simTime,frame:game.renderInfo().frame}));shots.push({file:name+'.png',before:b,after:a});};
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block',recordVideo:{dir:path.join(out,'video'),size:{width:844,height:390}}});context.setDefaultTimeout(60000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});const u=new URL(r.url());if(!confined(u.href)||!u.pathname.includes('/assets/')||!u.pathname.endsWith('.js'))return;responseTasks.push((async()=>{const b=await r.body(),n='dist/'+u.pathname.slice(base.pathname.length),expected=before[n];compiled.push({url:u.href,bytes:b.length,sha256:sha(b),match:!!expected&&b.length===expected.bytes&&sha(b)===expected.sha256});})().catch(e=>errors.push({kind:'asset',message:clean(e.message)})));});
 const verificationFiles=['index.html','feature-lab.html','development-plan.html','sounds.html',...(await fs.readdir(path.join(root,'dist/assets'))).filter(n=>n.endsWith('.js')).map(n=>'assets/'+n)];assert.equal(verificationFiles.length,8);
 for(const n of verificationFiles){const url=new URL(n,base);assert(confined(url.href));const r=await context.request.get(url.href,{maxRedirects:0,maxRetries:2});assert.equal(r.status(),200);const b=await r.body(),expected=before['dist/'+n];const row={name:n,bytes:b.length,sha256:sha(b),match:expected.bytes===b.length&&expected.sha256===sha(b)};fileChecks.push(row);assert(row.match,'Delivered bytes differ: '+n);}
 const url=new URL(base);url.search='weapon=longsword&foe=heinrich&foeWeapon=longsword';await page.goto(url.href,{waitUntil:'load'});await page.waitForFunction(()=>game?.player?.sword&&game?.combat&&game?.swordsmanshipDefault);await page.waitForLoadState('networkidle');
 await page.evaluate(()=>{
  const p=window.damageVisualProbe={events:[],applications:[],native:[],renderWindows:[],ai:{calls:0,freeAliveCalls:0},samples:[],phase:'menu',seq:0,nonfinite:0,installed:new WeakSet(),woundIds:new WeakMap(),nextWoundId:1,lastApplication:new WeakMap(),decalDraws:{},particleDraw:null};
  const role=f=>f===game.player?'player':f===game.enemy?'enemy':'other';
  const visible=o=>{for(let x=o;x;x=x.parent)if(!x.visible)return false;return true;};
  const compact=r=>Object.fromEntries(['type','zone','energy','severity','bleedPerSev','pass','finish','plate','helmet','speed','eff','thr','stuck','armorBlocked','armorGuarded'].map(k=>[k,r[k]??null]));
  const wound=w=>{if(!p.woundIds.has(w))p.woundIds.set(w,p.nextWoundId++);return{id:p.woundIds.get(w),part:w.part,type:w.type,severity:w.severity,bleed:w.bleed,local:w.local?.toArray(),stump:!!w.stump,soak:w.soak?.uuid??null,soaked:w.soaked??0};};
  const finite=f=>[...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite)));
  const health=f=>({role:role(f),alive:f.alive,armed:f.armed,state:f.state,blood:f.blood,bleed:f.bleed,wounds:f.wounds.map(wound),plate:{...f.plate},helmetIntegrity:f.helmetIntegrity,cloth:{...f.cloth},finite:finite(f)});
  const decal=o=>{const center=new game.THREE.Vector3();o.getWorldPosition(center);const projected=center.clone().project(game.camera);return{uuid:o.uuid,kind:o.userData.kind,parent:o.parent?.uuid??null,target:o.userData.mesh?.uuid??null,parentMatchesTarget:o.parent===o.userData.mesh,vertices:o.geometry?.attributes.position?.count??0,visible:visible(o),materialVisible:o.material?.visible,opacity:o.material?.opacity,transparent:o.material?.transparent,map:!!o.material?.map,w:o.userData.w,h:o.userData.h,position:center.toArray(),projected:projected.toArray(),draw:p.decalDraws[o.uuid]??null};};
  const decals=f=>{const out=[];for(const [part,group]of Object.entries(f.groups))group.traverse(o=>{if(o.userData?.kind&&o.userData?.mesh)out.push({part,...decal(o)});});return out;};
  const particles=game.player.scene.children.filter(o=>o.isInstancedMesh&&o.geometry.type==='BoxGeometry'&&o.material.isMeshBasicMaterial&&o.instanceMatrix.count===500&&o.frustumCulled===false);if(particles.length!==1)throw Error('Particle mesh is not uniquely identifiable');const mesh=particles[0];
  const particleState=()=>{const colors={},c=new game.THREE.Color();for(let i=0;i<mesh.count;i++){mesh.getColorAt(i,c);const k=c.getHexString();colors[k]=(colors[k]||0)+1;}return{uuid:mesh.uuid,count:mesh.count,colors,visible:visible(mesh),draw:p.particleDraw};};
  const prevDraw=mesh.onAfterRender;mesh.onAfterRender=function(...args){const result=prevDraw.apply(this,args);p.particleDraw={frame:game.renderInfo().frame,timeS:game.stats.simTime,count:this.count};return result;};
  function followDecals(f){for(const group of Object.values(f.groups))group.traverse(o=>{if(!o.userData?.kind||!o.userData?.mesh||p.decalDraws[o.uuid])return;const original=o.onAfterRender;p.decalDraws[o.uuid]={calls:0,firstFrame:null,lastFrame:null};o.onAfterRender=function(...args){const result=original.apply(this,args),r=p.decalDraws[this.uuid];r.calls++;r.lastFrame=game.renderInfo().frame;r.firstFrame??=r.lastFrame;r.timeS=game.stats.simTime;return result;};});}
  p.read=()=>({timeS:game.stats.simTime,state:game.state,frame:game.renderInfo().frame,phase:p.phase,player:health(game.player),enemy:health(game.enemy),particles:particleState(),decals:{player:decals(game.player),enemy:decals(game.enemy)},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),policies:{default:game.swordsmanshipDefault.active,v2:game.player.swordsmanshipModel,skill:game.player.skill.level,autoGuard:game.player.skill.autoGuard,arm:game.player.onehandArmModel,stance:game.player.stanceMemoryModel,roll:game.player.rollTargetModel,cut:game.combat.cutReactionModel,cutPlayer:game.combat.cutReactionFighter===game.player,limb:game.config.COMBAT.limbSeverTrial,finish:game.combat.finishRuleModel,gravity:game.world.gravity.y,enemyController:game.enemy.swordsmanshipModel??'legacy',enemyArm:game.enemy.onehandArmModel,aiLevel:game.ai.levelName,persona:game.ai.persona},input:{activeTouch:game.input.activeTouch,handHeld:game.player.handHeld,stick:{...game.input.stickMove},thrusts:game.player.skill.thrusts}});
  const fp=Object.getPrototypeOf(game.player),apply=fp.applyWound;fp.applyWound=function(h){const before=health(this),start=p.seq++,ret=apply.call(this,h),after=health(this);const row={seq:start,timeS:game.stats.simTime,victim:role(this),part:h.part,result:compact(h),before,after,newWounds:after.wounds.filter(w=>!before.wounds.some(x=>x.id===w.id))};p.applications.push(row);p.lastApplication.set(this,row);return ret;};
  const cp=Object.getPrototypeOf(game.combat),step=cp.afterStep;cp.afterStep=function(...args){if(!p.installed.has(this)){p.installed.add(this);const hook=this.hooks.onWound;this.hooks.onWound=function(att,vic,r,point,pr){const oldIds=new Set(decals(vic).map(d=>d.uuid)),before=health(vic),a=p.lastApplication.get(vic);const ret=hook.call(this,att,vic,r,point,pr);followDecals(vic);const after=health(vic);p.events.push({seq:p.seq++,timeS:game.stats.simTime,frame:game.renderInfo().frame,attacker:role(att),victim:role(vic),part:pr.v.part,result:compact(r),point:point.toArray(),local:r.local.toArray(),opened:r.type!=='blunt'&&r.severity>0,bloodSetting:game.settings.blood,application:a&&a.timeS===game.stats.simTime&&a.part===pr.v.part&&a.result.energy===r.energy?a.seq:null,before,after,newDecals:decals(vic).filter(d=>!oldIds.has(d.uuid)),particlesBeforeRender:particleState()});return ret;};}const ret=step.apply(this,args);if(!finite(game.player)||!finite(game.enemy))p.nonfinite++;if(game.stats.simTime>=(p.nextSample??0)){p.samples.push({timeS:game.stats.simTime,player:health(game.player),enemy:health(game.enemy),hand:game.player.handOffset.toArray(),stick:{...game.input.stickMove}});p.nextSample=game.stats.simTime+1;}return ret;};
  const ap=Object.getPrototypeOf(game.ai),update=ap.update;ap.update=function(...args){if(this===game.ai){p.ai.calls++;if(this.me.alive&&!this.me.feetHeld)p.ai.freeAliveCalls++;}return update.apply(this,args);};
  const rp=game.THREE.WebGLRenderer.prototype,render=rp.render;rp.render=function(...args){const ret=render.apply(this,args);if(p.events.length>(p.renderedEvents??0)&&p.renderWindows.length<100){p.renderedEvents=p.events.length;p.renderWindows.push({eventSeq:p.events.at(-1).seq,...p.read()});}return ret;};
  for(const type of['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<2500)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.id,timeS:game.stats.simTime,x:e.clientX,y:e.clientY});},true);
 });
 const menu=await page.evaluate(()=>damageVisualProbe.read());assert.deepEqual(menu.settings,seeds);assert.equal(menu.saved,settingsBytes);assert(menu.policies.default&&menu.policies.v2==='unified'&&menu.policies.skill===0&&!menu.policies.autoGuard&&menu.policies.arm==='manual'&&menu.policies.stance==='fresh'&&menu.policies.roll==='bounded'&&menu.policies.cut==='centerline'&&menu.policies.cutPlayer&&menu.policies.limb&&menu.policies.finish==='legacy'&&menu.policies.gravity===-9.81&&menu.policies.enemyController==='legacy'&&menu.policies.enemyArm==='legacy'&&menu.policies.aiLevel==='normal');
 await takeShot('menu');await page.locator('#btnStart').tap();await page.waitForFunction(()=>game.state==='fight');await takeShot('start');cdp=await context.newCDPSession(page);
 const pad=await page.locator('#moveStick').boundingBox();assert(pad,'Movement pad missing');const stick={x:pad.x+pad.width/2,y:pad.y+pad.height/2,id:1},hand={x:650,y:210,id:2};let fingers=[];
 async function send(type,points){inputRequests.push({type,points:points.map(p=>({...p}))});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});fingers=points.map(p=>({...p}));}
 const brief=()=>page.evaluate(()=>({t:game.stats.simTime,state:game.state,alive:game.player.alive&&game.enemy.alive,armed:game.player.armed,gap:Math.hypot(game.player.pelvisPos.x-game.enemy.pelvisPos.x,game.player.pelvisPos.z-game.enemy.pelvisPos.z),events:damageVisualProbe.events.length,opened:damageVisualProbe.events.some(e=>e.opened&&e.application!==null&&e.newDecals.some(d=>['cut','tear','stab'].includes(d.kind)&&d.vertices>0)),blocked:damageVisualProbe.events.some(e=>!e.opened&&e.newDecals.some(d=>['scratch','dent','bruise'].includes(d.kind)&&d.vertices>0))}));
 async function advance(delta){const b=await brief();await page.waitForFunction(t=>game.stats.simTime>=t||game.state!=='fight',Math.min(29,b.t+delta),{timeout:45000});return brief();}
 await page.evaluate(()=>{damageVisualProbe.phase='approach-and-cuts';});await send('touchStart',[stick]);let status=await brief(),cycles=0,seen=0;
 while(status.t<29&&status.state==='fight'&&status.alive&&status.armed&&cycles<12){
  stick.y=pad.y+pad.height/2-(status.gap>1.35?36:status.gap<.85?-24:0);await send('touchMove',[stick]);
  hand.x=670;hand.y=240;await send('touchStart',[stick,hand]);
  for(let n=1;n<=5;n++){hand.x=670-18*n;hand.y=240-22*n;await send('touchMove',[stick,hand]);status=await advance(.09);if(status.t>=29||status.state!=='fight'||!status.alive||!status.armed)break;}
  if(status.state==='fight'&&status.alive&&status.armed&&status.t<29){status=await advance(.15);for(let n=1;n<=5;n++){hand.x=580+23*n;hand.y=130+25*n;await send('touchMove',[stick,hand]);status=await advance(.07);if(status.t>=29||status.state!=='fight'||!status.alive||!status.armed)break;}}
  await send('touchEnd',[stick]);cycles++;status=await brief();
  if(status.events>seen){seen=status.events;await takeShot('events-'+String(cycles).padStart(2,'0'));status=await brief();}
  if(status.opened&&status.blocked)break;
  if(status.state==='fight'&&status.alive&&status.armed&&status.t<29)status=await advance(.18);
 }
 await send('touchEnd',[]);if(status.state==='fight'){await page.locator('#btnPause').tap();await page.waitForFunction(()=>game.state==='paused');}
 await page.waitForTimeout(80);await takeShot('end');episode=await page.evaluate(()=>{const p=damageVisualProbe;return{final:p.read(),events:p.events,applications:p.applications,native:p.native,renderWindows:p.renderWindows,ai:p.ai,samples:p.samples,nonfinite:p.nonfinite,decalDraws:p.decalDraws};});episode.menu=menu;episode.cycles=cycles;episode.stop=status;assert(episode.final.timeS<=30,'Episode exceeded 30 simulated seconds');assert.equal(episode.nonfinite,0);assert(episode.ai.freeAliveCalls>0);assert(episode.native.some(e=>e.target==='btnStart'));assert(episode.native.some(e=>['moveStick','moveKnob'].includes(e.target)));assert(episode.native.every(e=>e.trusted&&e.kind==='touch'));assert.deepEqual(episode.final.settings,seeds);assert.equal(episode.final.saved,settingsBytes);assert.equal(episode.final.policies.finish,'legacy');
 await Promise.all(responseTasks);assert(compiled.length&&compiled.every(x=>x.match));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page){await takeShot('failure');episode=await page.evaluate(()=>{const p=window.damageVisualProbe;return p?{final:p.read(),events:p.events,applications:p.applications,native:p.native,renderWindows:p.renderWindows,ai:p.ai,samples:p.samples,nonfinite:p.nonfinite,decalDraws:p.decalDraws}:null;});}}catch{}}
finally{
 if(cdp)await cdp.detach();await Promise.all(responseTasks);if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();const sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable;if(!pass)process.exitCode=1;
 const events=episode?.events??[],apps=episode?.applications??[];const opened=events.filter(e=>e.opened&&e.application!==null&&apps.some(a=>a.seq===e.application&&a.newWounds.length)&&e.newDecals.some(d=>['cut','tear','stab'].includes(d.kind)&&d.vertices>0));const blocked=events.filter(e=>!e.opened&&e.newDecals.some(d=>['scratch','dent','bruise'].includes(d.kind)&&d.vertices>0));
 const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),base:base.href,scenario:'ordinary longsword vs Heinrich with longsword; original normal character AI; one episode only',maxSimSeconds:30,settings:seeds,exposure:{openedEvents:opened.map(e=>e.seq),blockedOrBluntEvents:blocked.map(e=>e.seq),status:opened.length&&blocked.length?'both_exposed':'partially_or_not_exposed'},fileChecks,compiled,shots,errors,fatal,episode,inputRequests,limitations:['Input is authored native touch, not an exact headless replay.','onAfterRender proves submission, not unoccluded visible pixels; screenshots need inspection.','Blood OFF, natural severing, all-part anatomy, human readability and phone performance are not tested.'],tlsVerification:true,proxyRetained:!local,redirectsFollowed:false};
 await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,events:events.length,opened:opened.length,blocked:blocked.length,simTime:episode?.final?.timeS,fatal,out}));
}
