// Ordinary query-free progression UI with explicitly controlled Fighter.die terminal fixtures.
// This is not natural combat or human victory evidence. No RNG/pose/velocity assignments.
// PLAYWRIGHT_MODULE=... PLAYWRIGHT_BROWSERS_PATH=... node tools/browser/phase4_progression_20261008.mjs --out=<fresh-dir> --expect=baseline|fixed [--base=<own-base/>]
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/phase4_progression_20261008.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base|expect)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/phase4-progression-20261008/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString(), startedWall=performance.now(), wallDeadline=startedWall+240000;await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:false,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],lifecycle=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false,closingNormally=false;
assert(['baseline','fixed'].includes(args.expect));const expected=args.expect;
const flow={rounds:[]},checks={},clockLimits=[],findings=[];const entryURL=new URL(base);
await fs.copyFile(path.join(root,own),path.join(out,'executed-tool.mjs'));
const remaining=()=>wallDeadline-performance.now();
async function waitFor(fn,arg,maximum=15000){const timeout=Math.max(100,Math.min(maximum,remaining()-1500));try{return await page.waitForFunction(fn,arg,{timeout});}catch(e){if(e.name==='TimeoutError')clockLimits.push({wallMs:performance.now()-startedWall,maximum,remaining:remaining()});throw e;}}
const snap=()=>page.evaluate(()=>progressionProbe.read());
function clearInput(r){assert.equal(r.input.activeTouch,null);assert.equal(r.input.press,null);assert.deepEqual(r.input.pending,[0,0]);assert.deepEqual(r.input.stick,[0,0]);}
function policy(r){
 assert.equal(r.url,entryURL.href);assert.equal(r.stage.pinned,null);assert(r.default.active&&r.default.reason==='ordinary_entry'&&r.default.blockedBy.length===0);
 assert.equal(r.saved,settingsBytes);assert.deepEqual(r.settings,seeds);assert.equal(r.policies.startHold,2);assert.equal(r.policies.gravity,-9.81);assert.equal(r.policies.finish,'legacy');assert.equal(r.policies.limb,true);
 assert.equal(r.policies.stance,'fresh');assert.equal(r.policies.roll,r.player.gun?'legacy':'bounded');const cut=!r.player.gun&&r.player.edged?'centerline':'legacy';assert.equal(r.policies.cut,cut);assert.equal(r.policies.cutPlayer,cut==='centerline');
 const v2=!r.player.gun&&!['monohoshizao','lightsaber'].includes(r.player.weapon)&&!r.player.trialOnly;assert.equal(r.policies.v2,v2?'unified':'legacy');if(v2){assert.equal(r.policies.arm,'manual');assert.equal(r.policies.skill,0);assert.equal(r.policies.autoGuard,false);}assert.equal(r.policies.enemyController,'legacy');
}
function fresh(r){for(const f of [r.player,r.enemy]){assert.equal(f.alive,true);assert.equal(f.wounds,0);assert.equal(f.detached,0);assert.equal(f.blood,1);}assert(r.player.fightT<.6);}
async function shot(name){await page.screenshot({path:path.join(out,name+'.png')});shots.push(name+'.png');}
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(15000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}const relative=new URL(url).pathname.slice(base.pathname.length);if(!relative||relative==='development-plan.html'||relative.startsWith('assets/')&&relative.endsWith('.js')){const body=await r.body(),name='dist/'+(relative||'index.html'),wanted=before[name],digest=sha(body);compiled.push({name,url:clean(url),bytes:body.length,sha256:digest,match:!!wanted&&body.length===wanted.bytes&&digest===wanted.sha256,capture:'route.fetch APIResponse',delivery:'identical body passed to route.fulfill'});await route.fulfill({response:r,body});}else await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});});
 const life=(event,url)=>lifecycle.push({event,url:clean(url),wallMs:performance.now()-startedWall,closingNormally});page.on('crash',()=>{life('page-crash',page.url());errors.push({kind:'page-crash',url:clean(page.url())});});page.on('close',()=>{life('page-close',page.url());if(!closingNormally)errors.push({kind:'unexpected-page-close',url:clean(page.url())});});page.on('worker',worker=>{life('worker-open',worker.url());worker.on('close',()=>life('worker-close',worker.url()));});
 await page.goto(base.href,{waitUntil:'load',timeout:30000});await waitFor(()=>window.game?.ai&&game?.combat&&game?.swordsmanshipDefault);cdp=await context.newCDPSession(page);
 await page.evaluate(()=>{
  const p=window.progressionProbe={round:0,ids:new WeakMap(),nextId:1,steps:0,aiCalls:0,nonfinite:0,native:[],fixtures:[],frees:[],disposals:[],watched:new WeakSet(),firsts:[],seen:new WeakSet(),uiEvents:[],uiKey:null};
  const id=o=>{if(!p.ids.has(o))p.ids.set(o,p.nextId++);return p.ids.get(o);};const xy=v=>[v.x,v.y];
  const ui=()=>({menuShown:document.getElementById('menu').classList.contains('show'),title:document.getElementById('menuTitle').textContent,subtitle:document.getElementById('menuSub').textContent,start:document.getElementById('btnStart').textContent,resumeShown:getComputedStyle(document.getElementById('btnResume')).display!=='none',toast:document.getElementById('toast').textContent,toastShown:document.getElementById('toast').classList.contains('show'),foeName:document.querySelector('#foeIntro b')?.textContent??null});
  const health=f=>({id:id(f),name:f.name,weapon:f.weapon.id,gun:!!f.weapon.gun,edged:!!f.weapon.edged,trialOnly:!!f.weapon.trialOnly,state:f.state,alive:f.alive,armed:f.armed,fightT:f.fightT,feetHeld:f.feetHeld,blood:f.blood,consciousness:f.consciousness,wounds:f.wounds.length,detached:f.detachedParts?.size??0,cause:f.causeOfDeath??null});
  p.read=()=>({round:p.round,wallMs:performance.now(),url:location.href,state:game.state,simTime:game.stats.simTime,steps:p.steps,aiCalls:p.aiCalls,objects:{player:id(game.player),enemy:id(game.enemy),world:id(game.world),combat:id(game.combat),ai:id(game.ai),controller:id(game.player.skill),gait:id(game.player.gait)},player:health(game.player),enemy:health(game.enemy),ai:{level:game.ai.levelName,mode:game.ai.mode,phase:game.ai.phase,patience:game.ai.patience},ui:ui(),stage:{...game.stage},cards:{stage:game.draw.stage,t:game.draw.t,ids:[...game.draw.ids],pick:game.draw.pick},default:{...game.swordsmanshipDefault},policies:{v2:game.player.swordsmanshipModel??'legacy',arm:game.player.onehandArmModel,skill:game.player.skill.level,autoGuard:game.player.skill.autoGuard,stance:game.player.stanceMemoryModel,roll:game.player.rollTargetModel,cut:game.combat.cutReactionModel,cutPlayer:game.combat.cutReactionFighter===game.player,limb:game.config.COMBAT.limbSeverTrial,finish:game.combat.finishRuleModel,gravity:game.world.gravity.y,startHold:game.config.ARENA.startHold,enemyController:game.enemy.swordsmanshipModel??'legacy'},input:{enabled:game.input.enabled,activeTouch:game.input.activeTouch,press:game.input.press?{id:game.input.press.id}:null,pending:[game.input.handDX,game.input.handDY],stick:xy(game.input.stickMove)},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),renderer:game.renderInfo(),debris:game.debris.count()});
  p.watchVisuals=()=>{const roots=[],resources=[];for(const f of [game.player,game.enemy])for(const item of f.meshes){roots.push(item.group.uuid);item.group.traverse(o=>{for(const resource of [...(o.geometry&&!o.isSprite?[o.geometry]:[]),...(Array.isArray(o.material)?o.material:o.material?[o.material]:[])]){const token={uuid:resource.uuid,kind:resource.isMaterial?'material':'geometry'};resources.push(token);if(!p.watched.has(resource)){p.watched.add(resource);resource.addEventListener('dispose',()=>{if(p.disposals.length<1200)p.disposals.push({...token,round:p.round});});}}});}
   return{roots:[...new Set(roots)],resources:[...new Map(resources.map(x=>[x.uuid,x])).values()]};};
  p.retiredCheck=old=>({worldFreed:p.frees.includes(old.world),rootsStillAttached:old.roots.filter(uuid=>game.player.scene.getObjectByProperty('uuid',uuid)),disposedGeometry:old.resources.filter(x=>x.kind==='geometry'&&p.disposals.some(d=>d.uuid===x.uuid)).length,disposedMaterial:old.resources.filter(x=>x.kind==='material'&&p.disposals.some(d=>d.uuid===x.uuid)).length});
  const wp=Object.getPrototypeOf(game.world),free=wp.free;wp.free=function(...args){const token=id(this),ret=free.apply(this,args);p.frees.push(token);return ret;};
  const cp=Object.getPrototypeOf(game.combat),after=cp.afterStep;cp.afterStep=function(...args){const ret=after.apply(this,args);if(this===game.combat){p.steps++;if(!p.seen.has(game.player)){p.seen.add(game.player);p.firsts.push(p.read());}if(p.steps%24===0)for(const f of [game.player,game.enemy])if(![...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite))))p.nonfinite++;}return ret;};
  const ap=Object.getPrototypeOf(game.ai),update=ap.update;ap.update=function(...args){const ret=update.apply(this,args);if(this===game.ai)p.aiCalls++;return ret;};
  const obs=new MutationObserver(()=>{const current=ui(),key=JSON.stringify(current);if(key!==p.uiKey){p.uiKey=key;if(p.uiEvents.length<120)p.uiEvents.push({round:p.round,simTime:game.stats.simTime,wallMs:performance.now(),...current});}});for(const key of ['menu','menuTitle','menuSub','btnStart','btnResume','toast','foeIntro'])obs.observe(document.getElementById(key),{attributes:true,childList:true,subtree:true});
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<200)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.closest?.('button')?.id||e.target.id,card:e.target.closest?.('.wcard')?.dataset.i??null,round:p.round,simTime:game.stats.simTime,x:e.clientX,y:e.clientY});},true);
  // Explicit protocol write through the real Fighter API, never relabeled as a natural kill.
  p.fixture=target=>{const row={kind:'controlled_terminal_fixture',api:`game.${target}.die('기절')`,round:p.round,before:p.read()};game[target].die('기절');row.after=p.read();p.fixtures.push(row);return row;};
  p.export=()=>({steps:p.steps,aiCalls:p.aiCalls,nonfiniteSamples:p.nonfinite,native:p.native,fixtures:p.fixtures,frees:p.frees,disposalCounts:{geometry:p.disposals.filter(x=>x.kind==='geometry').length,material:p.disposals.filter(x=>x.kind==='material').length},firsts:p.firsts,uiEvents:p.uiEvents,final:p.read()});
 });
 flow.menu=await snap();policy(flow.menu);
 async function send(type,points){inputRequests.push({type,points:points.map(x=>({...x}))});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});}
 async function nativeAdvance(){const before=await snap();await send('touchStart',[{x:670,y:240,id:1}]);await send('touchMove',[{x:650,y:205,id:1}]);const held=await snap();assert.notEqual(held.input.activeTouch,null);await waitFor(s=>progressionProbe.steps>s,before.steps,5000);await send('touchEnd',[]);const after=await snap();assert(after.steps>before.steps);return{beforeSteps:before.steps,afterSteps:after.steps,activeTouch:held.input.activeTouch};}
 async function enter(round,stage,foe,retired){
  await page.evaluate(n=>{progressionProbe.round=n;},round);const row={round,wallStart:performance.now()-startedWall};flow.rounds.push(row);await page.locator('#btnStart').tap();await waitFor(()=>game.state==='draw'&&game.draw.stage==='choose'&&game.draw.t>=.5,null,45000);const offer=await snap();policy(offer);row.offered={stage:offer.stage,cards:offer.cards,foe:offer.enemy.name,foeIntro:offer.ui.foeName};assert.equal(offer.stage.id,stage);assert.equal(offer.enemy.name,foe);assert.equal(offer.ui.foeName,foe);
  await page.locator('#draw button[data-i="0"]').tap();await waitFor(()=>game.state==='fight'||game.draw.stage==='reveal'&&game.draw.t>=1||game.draw.stage==='fly',null,45000);const reveal=await snap();if(reveal.state==='draw'&&reveal.cards.stage==='reveal')await page.locator('#draw button[data-i="0"]').tap();await waitFor(()=>game.state==='fight'&&game.player.fightT>0,null,45000);
  row.started=await snap();policy(row.started);fresh(row.started);assert.equal(row.started.player.weapon,offer.cards.ids[0]);assert.equal(row.started.enemy.weapon,offer.cards.ids[2]);assert.equal(row.started.stage.id,stage);assert.equal(row.started.enemy.name,foe);
  if(retired){for(const key of Object.keys(row.started.objects))assert.notEqual(row.started.objects[key],retired.objects[key]);row.retired=await page.evaluate(old=>progressionProbe.retiredCheck(old),{world:retired.objects.world,...retired.visuals});assert(row.retired.worldFreed);assert.deepEqual(row.retired.rootsStillAttached,[]);assert(row.retired.disposedGeometry>0&&row.retired.disposedMaterial>0);}
  row.visuals=await page.evaluate(()=>progressionProbe.watchVisuals());row.input=await nativeAdvance();console.log(JSON.stringify({event:'entered',round,stage,foe,weapon:row.started.player.weapon,foeWeapon:row.started.enemy.weapon,simTime:row.started.simTime,wallMs:performance.now()-startedWall}));return row;
 }
 const first=await enter(1,'poseidon','하인리히 도른');
 flow.winFixture=await page.evaluate(()=>progressionProbe.fixture('enemy'));await waitFor(()=>document.getElementById('toast').textContent==='승리'&&game.state==='fight');flow.winLatched=await snap();
 await page.locator('#btnPause').tap();await waitFor(()=>game.state==='paused');flow.earlyWinMenu=await snap();clearInput(flow.earlyWinMenu);assert(flow.earlyWinMenu.ui.menuShown);await shot('early-win-menu');
 const early=flow.earlyWinMenu.ui;findings.push({id:'finished_pause_menu',contract:early.title==='승리'&&early.start==='다음 상대'&&!early.resumeShown,observed:{title:early.title,start:early.start,resumeShown:early.resumeShown}});
 if(expected==='baseline'){assert.equal(early.title,'일시정지');assert.equal(early.start,'처음부터 다시');assert.equal(early.resumeShown,true);}else assert(findings.at(-1).contract);
 const second=await enter(2,'clearing','오소리 브란',{objects:first.started.objects,visuals:first.visuals});
 flow.lossFixture=await page.evaluate(()=>progressionProbe.fixture('player'));await waitFor(()=>document.getElementById('toast').textContent==='패배'&&game.state==='fight');flow.lossLatched=await snap();flow.laterEnemyFixture=await page.evaluate(()=>progressionProbe.fixture('enemy'));
 await waitFor(()=>game.state==='paused'&&document.getElementById('menu').classList.contains('show'),null,70000);flow.delayedLossMenu=await snap();clearInput(flow.delayedLossMenu);await shot('delayed-loss-menu');
 const late=flow.delayedLossMenu.ui;findings.push({id:'latched_loss_menu',contract:late.title==='패배'&&late.start==='다시 싸우기'&&!late.resumeShown,observed:{title:late.title,start:late.start,resumeShown:late.resumeShown},firstToast:flow.lossLatched.ui.toast});
 if(expected==='baseline'){assert.equal(late.title,'승리');assert.equal(late.start,'다음 상대');assert.equal(late.resumeShown,false);}else assert(findings.at(-1).contract);
 const third=await enter(3,'clearing','오소리 브란',{objects:second.started.objects,visuals:second.visuals});
 await page.locator('#btnPause').tap();await waitFor(()=>game.state==='paused');flow.finalPaused=await snap();clearInput(flow.finalPaused);assert.equal(flow.finalPaused.ui.title,'일시정지');assert.equal(flow.finalPaused.ui.start,'처음부터 다시');assert.equal(flow.finalPaused.ui.resumeShown,true);await shot('fresh-same-foe-restart');
 episode=await page.evaluate(()=>progressionProbe.export());checks.native=episode.native.every(x=>x.trusted&&x.kind==='touch')&&episode.native.length>0;checks.threeRounds=flow.rounds.length===3;checks.threeExplicitFixtures=episode.fixtures.length===3;checks.finiteSamples=episode.nonfiniteSamples===0;checks.defaultsAndRosters=true;checks.retirementObserved=flow.rounds.slice(1).every(r=>r.retired.worldFreed&&r.retired.disposedGeometry>0&&r.retired.disposedMaterial>0);checks.simulationBound=episode.final.simTime<=8;
 checks.expectedEvidence=expected==='baseline'?findings.every(x=>!x.contract):findings.every(x=>x.contract);
 // Public delivery only: combat is paused and exported before this static navigation.
 if(!local){await cdp.detach();cdp=null;const response=await page.goto(new URL('development-plan.html',base).href,{waitUntil:'load',timeout:15000});assert.equal(response.status(),200);const delivered=compiled.findLast(x=>x.name==='dist/development-plan.html');assert(delivered?.match);flow.phonePlan={sha256:delivered.sha256,match:delivered.match,views:[]};for(const viewport of [{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(viewport);const layout=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,firstHeading:document.querySelector('main h2')?.textContent??null,firstSummary:document.querySelector('main h2 + p strong')?.textContent??null}));assert.equal(layout.scrollWidth,layout.width);assert.equal(layout.firstHeading,'4단계 · 경기 결과와 다음 판 연결 · 10/08');assert.equal(layout.firstSummary,'승패 안내의 두 불일치와 파손 무기의 남은 충돌을 수정했다.');flow.phonePlan.views.push(layout);await shot(`phone-plan-${viewport.width}x${viewport.height}`);}checks.phonePlan=true;}
 checks.compiledExact=compiled.some(x=>x.name.startsWith('dist/assets/main-'))&&compiled.some(x=>x.name==='dist/index.html')&&compiled.every(x=>x.match);assert.deepEqual(errors,[]);assert(Object.values(checks).every(Boolean));pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page&&!episode)episode=await page.evaluate(()=>window.progressionProbe?.export()??null);}catch{}}
finally{
 closingNormally=true;if(cdp)await cdp.detach().catch(()=>{});if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();const sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;checks.wallBudget=performance.now()-startedWall<=240000;pass=pass&&sourceStable&&checks.wallBudget&&errors.length===0;if(!pass)process.exitCode=1;
 const report={pass,passMeaning:expected==='baseline'?'Successful reproduction of both known UI mismatches plus controlled progression integrity; NOT a correct-game verdict.':'Correct terminal UI latch/pause and progression contracts under three explicit controlled Fighter.die fixtures.',contractsPass:findings.length===2&&findings.every(x=>x.contract),expected,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),wallMs:performance.now()-startedWall,base:base.href,entryURL:entryURL.href,scenario:'Query-free card0; fixture enemy death then early pause→next stage Bran; fixture player death latched before later enemy death→result delay→same-stage Bran restart. Three rounds only.',settings:seeds,checks,findings,clockLimits,flow,episode,compiled,lifecycle,errors,fatal,inputRequests,shots,limits:['Explicit terminal API calls intentionally change fighter state. This is UI/progression/lifecycle validation, not natural damage, combat victory, human play or difficulty evidence.','No RNG, pose, velocity, direct alive flag, stage or AI state assignment. Physics advances through the real game RAF; all buttons/cards/hand inputs are trusted native touches.','Pause on a finished bout and delayed result must use the same latched outcome; the browser observes menus and actual next roster rather than changing internal round flags.','Disposal observers cover registered fighter visual roots/resources and the original world.free call; counts are not GPU byte or long-session performance claims.','The card draw may naturally choose guns/withheld-v2 weapons or Bran alternative weapons. Defaults are checked from each actual weapon.','Card eligibility .45s/skip .95s use capped game animation clocks; 45s waits accommodate cloud software rendering. Run cap240wall seconds,8sim seconds, no automatic retry/seed search.'],tlsVerification:true,proxyRetained:!local,redirectsFollowed:false};
 await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,contractsPass:report.contractsPass,expected,sourceStable,findings,simTime:episode?.final?.simTime,wallMs:report.wallMs,fatal,out}));
}
