// Real trusted pistol shot and explicitly controlled reload-state fixture; original audio and RAF preserved.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/revolver_audio_20261008.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/revolver-audio-20261008/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString(), startedWall=performance.now(), wallDeadline=startedWall+250000;await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:true,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],lifecycle=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false,closingNormally=false;
const flow={},checks={},clockLimits=[];const entryURL=new URL('?weapon=pistol&foe=heinrich&foeWeapon=longsword',base);
await fs.copyFile(path.join(root,own),path.join(out,'executed-tool.mjs'));
const remaining=()=>wallDeadline-performance.now();
async function waitFor(fn,arg,maximum=15000){const timeout=Math.max(100,Math.min(maximum,remaining()-1500));try{return await page.waitForFunction(fn,arg,{timeout});}catch(e){if(e.name==='TimeoutError')clockLimits.push({wallMs:performance.now()-startedWall,maximum,remaining:remaining()});throw e;}}
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(15000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}const relative=new URL(url).pathname.slice(base.pathname.length);if(!relative||relative==='development-plan.html'||relative.startsWith('assets/')&&relative.endsWith('.js')){const body=await r.body(),name='dist/'+(relative||'index.html'),wanted=before[name],digest=sha(body);compiled.push({name,url:clean(url),bytes:body.length,sha256:digest,match:!!wanted&&body.length===wanted.bytes&&digest===wanted.sha256,capture:'route.fetch APIResponse',delivery:'identical body passed to route.fulfill'});await route.fulfill({response:r,body});}else await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});});
 const life=(event,url)=>lifecycle.push({event,url:clean(url),wallMs:performance.now()-startedWall,closingNormally});page.on('crash',()=>{life('page-crash',page.url());errors.push({kind:'page-crash',url:clean(page.url())});});page.on('close',()=>{life('page-close',page.url());if(!closingNormally)errors.push({kind:'unexpected-page-close',url:clean(page.url())});});page.on('worker',worker=>{life('worker-open',worker.url());worker.on('close',()=>life('worker-close',worker.url()));});
 await page.goto(entryURL.href,{waitUntil:'load',timeout:30000});await waitFor(()=>window.game?.ai&&game?.combat&&game?.swordsmanshipDefault);cdp=await context.newCDPSession(page);
 await page.evaluate(()=>{
  const p=window.revolverProbe={steps:0,aiCalls:0,native:[],events:[],shotCalls:[],sourceData:new WeakMap(),fixtures:[],round:1,nonfinite:0};
  const gun=f=>f.gun?Object.fromEntries(['cool','pending','shots','hits','ammo','reloading','t'].map(k=>[k,f.gun[k]])):null;
  p.read=()=>({state:game.state,simTime:game.stats.simTime,steps:p.steps,aiCalls:p.aiCalls,player:{name:game.player.name,alive:game.player.alive,armed:game.player.armed,weapon:game.player.weapon.id,wounds:game.player.wounds.length,gun:gun(game.player)},enemy:{name:game.enemy.name,alive:game.enemy.alive,weapon:game.enemy.weapon.id},sound:{on:game.sound.on,context:game.sound.ctx?.state,master:game.sound.master?.gain.value,stats:{...game.sound.stats}},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),stage:game.stage.id,default:{...game.swordsmanshipDefault},policies:{gravity:game.world.gravity.y,finish:game.combat.finishRuleModel,limb:game.config.COMBAT.limbSeverTrial},input:{activeTouch:game.input.activeTouch,pending:[game.input.handDX,game.input.handDY],taps:game.input.taps}});
  const sound=game.sound,event=sound.event,shot=sound.gunshot;let inShot=false;
  sound.gunshot=function(...args){const row={round:p.round,simTime:game.stats.simTime,on:this.on};p.shotCalls.push(row);inShot=true;try{return shot.apply(this,args);}finally{inShot=false;}};
  sound.event=function(options){const ev=event.call(this,options),row={round:p.round,shot:inShot,simTime:game.stats.simTime,gunT:game.player.gun?.t,cool:game.player.gun?.cool,reloading:game.player.gun?.reloading,gain:options.gain,actualGain:ev.out.gain.value,prio:options.prio,metal:options.bus===this.metalBus,audioTime:this.ctx.currentTime,context:this.ctx.state};queueMicrotask(()=>{row.sources=ev.srcs.map(s=>({...p.sourceData.get(s),buffer:!!s.buffer,duration:s.buffer?.duration??null}));row.end=ev.end;row.duration=ev.end-ev.start;if((row.shot||row.prio===1&&row.metal)&&p.events.length<160)p.events.push(row);});return ev;};
  p.watchAudio=()=>{const c=game.sound.ctx,create=c.createBufferSource;c.createBufferSource=function(...args){const src=create.apply(this,args),data={start:[],stop:[]};p.sourceData.set(src,data);for(const key of ['start','stop']){const original=src[key];src[key]=function(...a){const result=original.apply(this,a);data[key].push(a);return result;};}return src;};};
  const cp=Object.getPrototypeOf(game.combat),after=cp.afterStep;cp.afterStep=function(...a){const result=after.apply(this,a);if(this===game.combat){p.steps++;if(p.steps%60===0)for(const f of [game.player,game.enemy])if(![...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite))))p.nonfinite++;}return result;};
  const ap=Object.getPrototypeOf(game.ai),update=ap.update;ap.update=function(...a){const result=update.apply(this,a);if(this===game.ai)p.aiCalls++;return result;};
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<100)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.closest?.('button')?.id||e.target.id,round:p.round,simTime:game.stats.simTime});},true);
  p.fixture=()=>{const before=p.read(),g=game.player.gun;g.ammo=0;g.reloading=true;g.cool=9;g.pending=-1;const row={kind:'controlled_reload_fixture',writes:{ammo:0,reloading:true,cool:9,pending:-1},before,after:p.read()};p.fixtures.push(row);return row;};
  p.export=()=>({steps:p.steps,aiCalls:p.aiCalls,native:p.native,events:p.events,shotCalls:p.shotCalls,fixtures:p.fixtures,nonfinite:p.nonfinite,final:p.read()});
 });
 const snap=()=>page.evaluate(()=>revolverProbe.read());
 const pause=async()=>{await page.locator('#btnPause').tap();await waitFor(()=>game.state==='paused');};
 await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.sound.ctx?.state==='running',null,45000);flow.start=await snap();assert.equal(flow.start.player.weapon,'pistol');assert.equal(flow.start.player.gun.ammo,6);assert(flow.start.sound.on);await page.evaluate(()=>revolverProbe.watchAudio());
 await page.touchscreen.tap(675,230);await waitFor(()=>revolverProbe.shotCalls.length===1&&game.player.gun.shots===1,null,12000);flow.afterShot=await snap();assert.equal(flow.afterShot.player.gun.ammo,5);
 flow.fixture=await page.evaluate(()=>revolverProbe.fixture());console.log(JSON.stringify({event:'shot-and-reload-fixture',snapshot:flow.afterShot}));
 await waitFor(()=>game.player.gun.cool<6.5||game.state!=='fight',null,60000);assert.equal((await snap()).state,'fight','Original combat ended before the reload pause gate');await pause();flow.paused=await snap();await page.waitForTimeout(800);flow.pausedLater=await snap();assert.equal(flow.pausedLater.steps,flow.paused.steps);assert.equal(flow.pausedLater.player.gun.cool,flow.paused.player.gun.cool);
 await page.locator('[data-setting="sound"]').tap();flow.muted=await snap();assert(!flow.muted.sound.on&&!flow.muted.settings.sound);await page.locator('[data-setting="sound"]').tap();flow.unmuted=await snap();assert(flow.unmuted.sound.on&&flow.unmuted.settings.sound);await page.locator('#btnResume').tap();await waitFor(()=>game.state==='fight');
 await waitFor(()=>!game.player.gun.reloading||game.state!=='fight',null,150000);flow.completed=await snap();assert.equal(flow.completed.state,'fight','Original combat ended before reload completion');assert.equal(flow.completed.player.gun.ammo,6);assert.equal(flow.completed.player.gun.reloading,false);assert.equal(flow.completed.player.gun.shots,1);assert(flow.completed.player.gun.t-flow.fixture.after.player.gun.t>=9);assert(flow.completed.player.gun.t-flow.fixture.after.player.gun.t<9.5);
 await pause();await page.screenshot({path:path.join(out,'reload-completed.png')});shots.push('reload-completed.png');
 flow.audio=await page.evaluate(()=>revolverProbe.export());const shotEvents=flow.audio.events.filter(e=>e.shot);assert.equal(shotEvents.length,1);assert(Math.abs(shotEvents[0].gain-1.955)<1e-9);assert.equal(shotEvents[0].actualGain,Math.fround(1.955));assert(shotEvents[0].sources.length>=2&&shotEvents[0].sources.every(s=>s.start.length===1));
 const loadEvents=flow.audio.events.filter(e=>!e.shot&&e.metal&&e.prio===1&&e.sources.length===2&&e.sources.every(s=>s.start?.length===1)&&Math.abs(e.sources[1].start[0][0]-e.sources[0].start[0][0]-.1)<1e-5);flow.loadEvents=loadEvents;assert.equal(loadEvents.length,6);for(const e of loadEvents){assert.equal(e.gain,.75);assert.equal(e.actualGain,.75);assert(e.sources.every(s=>s.start.length===1&&s.stop.length===1&&s.buffer));}const expectedTimes=Array.from({length:6},(_,i)=>.9+7.3*(i+.5)/6);for(let i=0;i<6;i++)assert(Math.abs(loadEvents[i].gunT-flow.fixture.after.player.gun.t-expectedTimes[i])<.025);
 await page.evaluate(()=>{revolverProbe.oldPlayer=game.player;revolverProbe.oldWorld=game.world;revolverProbe.round=2;});await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.player!==revolverProbe.oldPlayer,null,45000);flow.restart=await snap();assert.equal(flow.restart.player.gun.ammo,6);assert.equal(flow.restart.player.gun.reloading,false);assert.equal(flow.restart.player.gun.shots,0);assert.equal(flow.restart.player.wounds,0);assert(await page.evaluate(()=>game.world!==revolverProbe.oldWorld));await pause();episode=await page.evaluate(()=>revolverProbe.export());
 Object.assign(checks,{shotGain:true,sixLoads:true,reloadNineSeconds:true,pauseStopsScheduler:true,muteAndResume:true,restartFresh:true,native:episode.native.length>0&&episode.native.every(e=>e.trusted&&e.kind==='touch'),finite:episode.nonfinite===0,oneExplicitFixture:episode.fixtures.length===1,preferencesRestored:episode.final.saved===settingsBytes,compiledExact:compiled.some(x=>x.name.startsWith('dist/assets/main-'))&&compiled.every(x=>x.match)});assert(Object.values(checks).every(Boolean));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page)episode=await page.evaluate(()=>revolverProbe?.export()??null);}catch{}}
finally{closingNormally=true;if(cdp)await cdp.detach().catch(()=>{});if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable&&errors.length===0&&performance.now()-startedWall<=250000;if(!pass)process.exitCode=1;const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),wallMs:performance.now()-startedWall,entryURL:entryURL.href,settings:seeds,checks,flow,episode,compiled,lifecycle,errors,fatal,clockLimits,shots,tlsVerification:true,limits:['Exactly one natural trusted pistol tap; reload begins through explicit ammo=0,reloading=true,cool=9,pending=-1 fixture, not six natural shots or a natural-combat completion.','Original AI, damage, RNG, RAF/physics and audio function results are retained. Audio scheduling/gain is observed, not human loudness or speaker quality.','No seed search, opponent disabling, teleporting, accelerated clock or synthetic audio event. Reload may remain unexposed if original combat ends first.','Source start calls and gain nodes prove Web Audio scheduling, not acoustic playback from a physical device.']};await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,checks,errors,fatal,out}));}
