// Opening fire gate and reload completion through native game paths; one explicit ammo fixture.
// Previous run copies remain in the earlier delivery receipt; this is the 10/08 completion follow-up.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
// Root-confirmed contract; exact 1.1 target geometry is verified by the separate native lane.
const INSERT_GAP=(7.3/6)*.8*.8;
const EXPECT={energy:80,cooldown:.8,reload:8,insertGap:INSERT_GAP,insertTimes:Array.from({length:6},(_,i)=>7.2-INSERT_GAP*(5-i)),gains:{open:.65*1.2,insert:.95*1.2,close:1.44},aimEnvelopeScale:1.1,aimSide:.30,aimHeightSway:.20,randomHoldMax:.14*1.4,aimRaySafetyBound:.40};
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/revolver_tuning_20261008.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/revolver-completion-20261008/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString(), startedWall=performance.now(), wallDeadline=startedWall+300000;await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:true,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],lifecycle=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false,closingNormally=false;
const flow={protocol:{version:'opening-gate-reload-v3',revisionReason:'User authorized the first2s fire gate and reload completion refinement',firstTwoTaps:'Early taps rejected; two later real shots with one ammo=1 fixture; no RNG assignment or seed search',retreat:'native left joystick offset(+24,+32) px, held during reload; release for Pause, reapply after Resume'},retreat:[]},checks={},clockLimits=[];const entryURL=new URL('?weapon=pistol&foe=heinrich&foeWeapon=longsword',base);
await fs.copyFile(path.join(root,own),path.join(out,'executed-tool.mjs'));
const remaining=()=>wallDeadline-performance.now();
async function waitFor(fn,arg,maximum=15000){const timeout=Math.max(100,Math.min(maximum,remaining()-1500));try{return await page.waitForFunction(fn,arg,{timeout});}catch(e){if(e.name==='TimeoutError')clockLimits.push({wallMs:performance.now()-startedWall,maximum,remaining:remaining()});throw e;}}
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(15000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}const relative=new URL(url).pathname.slice(base.pathname.length);if(!relative||relative==='development-plan.html'||relative.startsWith('assets/')&&relative.endsWith('.js')||relative.startsWith('sfx/revolver/')&&relative.endsWith('.wav')){const body=await r.body(),name='dist/'+(relative||'index.html'),wanted=before[name],digest=sha(body);compiled.push({name,url:clean(url),bytes:body.length,sha256:digest,match:!!wanted&&body.length===wanted.bytes&&digest===wanted.sha256,capture:'route.fetch APIResponse',delivery:'identical body passed to route.fulfill'});await route.fulfill({response:r,body});}else await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});});
 const life=(event,url)=>lifecycle.push({event,url:clean(url),wallMs:performance.now()-startedWall,closingNormally});page.on('crash',()=>{life('page-crash',page.url());errors.push({kind:'page-crash',url:clean(page.url())});});page.on('close',()=>{life('page-close',page.url());if(!closingNormally)errors.push({kind:'unexpected-page-close',url:clean(page.url())});});page.on('worker',worker=>{life('worker-open',worker.url());worker.on('close',()=>life('worker-close',worker.url()));});
 await page.goto(entryURL.href,{waitUntil:'load',timeout:30000});await waitFor(()=>window.game?.ai&&game?.combat&&game?.swordsmanshipDefault);cdp=await context.newCDPSession(page);
 const expectedWavs=Object.entries(before).filter(([name])=>/^dist\/sfx\/revolver\/[^/]+\.wav$/.test(name)).map(([name,m])=>({file:name.slice('dist/'.length),...m}));assert.equal(expectedWavs.length,8);
 await page.evaluate(expectedWavs=>{
  const p=window.revolverProbe={steps:0,aiCalls:0,skillUpdates:0,aim:[],wounds:[],native:[],events:[],shotCalls:[],sourceData:new WeakMap(),decodedBuffers:new WeakMap(),decoded:[],decodeTasks:[],fixtures:[],round:1,nonfinite:0,collectAim:true};
  const gun=f=>f.gun?Object.fromEntries(['cool','pending','shots','hits','ammo','reloading','t','since','h'].map(k=>[k,f.gun[k]])):null;
  p.read=()=>({state:game.state,simTime:game.stats.simTime,fightT:game.player.fightT,feetHeld:game.player.feetHeld,steps:p.steps,aiCalls:p.aiCalls,player:{name:game.player.name,alive:game.player.alive,state:game.player.state,armed:game.player.armed,weapon:game.player.weapon.id,wounds:game.player.wounds.length,pelvis:{...game.player.bodies.pelvis.translation()},move:{x:game.player.move.x,y:game.player.move.y},gun:gun(game.player)},enemy:{name:game.enemy.name,alive:game.enemy.alive,weapon:game.enemy.weapon.id},sound:{on:game.sound.on,context:game.sound.ctx?.state,master:game.sound.master?.gain.value},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),policies:{gravity:game.world.gravity.y,finish:game.combat.finishRuleModel,limb:game.config.COMBAT.limbSeverTrial},input:{activeTouch:game.input.activeTouch,pending:[game.input.handDX,game.input.handDY],taps:game.input.taps,stick:{...game.input.stickMove}}});
  const sound=game.sound,event=sound.event,shot=sound.gunshot;let inShot=false;
  sound.gunshot=function(...args){p.shotCalls.push({round:p.round,simTime:game.stats.simTime,on:this.on});inShot=true;try{return shot.apply(this,args);}finally{inShot=false;}};
  sound.event=function(options){const ev=event.call(this,options),row={round:p.round,shot:inShot,simTime:game.stats.simTime,gunT:game.player.gun?.t,cool:game.player.gun?.cool,reloading:game.player.gun?.reloading,gain:options.gain,actualGain:ev.out.gain.value,prio:options.prio,metal:options.bus===this.metalBus,context:this.ctx.state};queueMicrotask(()=>{row.sources=ev.srcs.map(s=>({...p.sourceData.get(s),duration:s.buffer?.duration??null,recording:p.decodedBuffers.get(s.buffer)??null}));if((row.shot||row.prio===1&&row.metal)&&p.events.length<160)p.events.push(row);});return ev;};
  p.watchAudio=()=>{const c=game.sound.ctx,create=c.createBufferSource,decode=c.decodeAudioData;c.decodeAudioData=function(bytes,ok,bad){const copy=bytes.slice(0),hash=crypto.subtle.digest('SHA-256',copy).then(raw=>Array.from(new Uint8Array(raw),n=>n.toString(16).padStart(2,'0')).join(''));const mark=buffer=>{if(p.decodedBuffers.has(buffer))return;const row={id:p.decoded.length+1,bytes:copy.byteLength,sha256:null,file:null,sampleRate:buffer.sampleRate,length:buffer.length,duration:buffer.duration};p.decodedBuffers.set(buffer,row);p.decoded.push(row);p.decodeTasks.push(hash.then(sha256=>{row.sha256=sha256;row.file=expectedWavs.find(w=>w.sha256===sha256&&w.bytes===row.bytes)?.file??null;}));};const result=decode.call(this,bytes,typeof ok==='function'?function(buffer){mark(buffer);return ok.apply(this,arguments);}:undefined,bad);result?.then(mark,()=>{});return result;};c.createBufferSource=function(...args){const src=create.apply(this,args),data={start:[],stop:[]};p.sourceData.set(src,data);for(const key of ['start','stop']){const original=src[key];src[key]=function(...a){const result=original.apply(this,a);data[key].push(a);return result;};}return src;};};
  const sp=Object.getPrototypeOf(game.player.skill),skillUpdate=sp.update,vec=v=>({x:v.x,y:v.y,z:v.z});sp.update=function(...args){const ret=skillUpdate.apply(this,args);if(this===game.player.skill){p.skillUpdates++;const f=game.player,g=f.gun;if(p.collectAim&&p.skillUpdates%6===0&&p.aim.length<80&&g&&!g.reloading&&g.since>.25&&this.thrustPose.w===1&&(f.state==='stand'||f.state==='kneel')){const T=game.THREE,q=new T.Quaternion().copy(f.sword.rotation()),muzzleOrigin=f.bladePoint(1,new T.Vector3()).add(new T.Vector3(f.weapon.muzzleX??0,0,0).applyQuaternion(q)),muzzleDir=new T.Vector3(0,1,0).applyQuaternion(q),commandDir=new T.Vector3(...this.thrustPose.dir).applyQuaternion(f.yaw),commandOrigin=new T.Vector3(...this.thrustPose.hand).applyQuaternion(f.yaw).add(new T.Vector3().copy(f.bodies.chest.translation())),bodyLine=['pelvis','abdomen','chest',...(!f.foe.decapitated&&f.foe.bodies.head?['head']:[])].map(k=>new T.Vector3().copy(f.foe.bodies[k].translation())),ray=new T.Ray(commandOrigin,commandDir),distance=Math.sqrt(Math.min(...bodyLine.slice(1).map((b,i)=>ray.distanceSqToSegment(bodyLine[i],b))));p.aim.push({simTime:game.stats.simTime,gunT:g.t,h:g.h,rs:{...g.rs},rsB:{...g.rsB},rsH:g.rsH,rsT:g.rsT,commandDir:vec(commandDir),commandRayTorsoDistance:distance,physicalMuzzle:{origin:vec(muzzleOrigin),dir:vec(muzzleDir)}});}}return ret;};
  const cp=Object.getPrototypeOf(game.combat),after=cp.afterStep;cp.afterStep=function(...a){const result=after.apply(this,a);if(this===game.combat){p.steps++;if(p.steps%60===0)for(const f of [game.player,game.enemy])if(![...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite))))p.nonfinite++;}return result;};
  const fp=Object.getPrototypeOf(game.player),wound=fp.applyWound;fp.applyWound=function(h,...rest){const ret=wound.call(this,h,...rest);if(h.gun&&p.wounds.length<12)p.wounds.push({round:p.round,simTime:game.stats.simTime,victim:this.name,part:h.part,zone:h.zone,energy:h.energy,type:h.type,pass:h.pass,helmet:h.helmet});return ret;};
  const ap=Object.getPrototypeOf(game.ai),update=ap.update;ap.update=function(...a){const result=update.apply(this,a);if(this===game.ai)p.aiCalls++;return result;};
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<100)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.closest?.('button')?.id||e.target.id,round:p.round,simTime:game.stats.simTime});},true);
  p.fixture=()=>{const before=p.read();game.player.gun.ammo=1;p.collectAim=false;const row={kind:'controlled_last_round_ammo_fixture',writes:{ammo:1},before,after:p.read()};p.fixtures.push(row);return row;};
  p.export=()=>({steps:p.steps,aiCalls:p.aiCalls,native:p.native,aim:p.aim,wounds:p.wounds,events:p.events,shotCalls:p.shotCalls,decoded:p.decoded.filter(d=>d.file),fixtures:p.fixtures,nonfinite:p.nonfinite,final:p.read()});
 },expectedWavs);
 const snap=()=>page.evaluate(()=>revolverProbe.read());const pause=async()=>{await page.locator('#btnPause').tap();await waitFor(()=>game.state==='paused');};
 async function retreatStart(label){const box=await page.locator('#moveStick').boundingBox();assert(box);const center={x:box.x+box.width/2,y:box.y+box.height/2,id:88};for(const [type,touchPoints] of [['touchStart',[center]],['touchMove',[{...center,x:center.x+24,y:center.y+32}]]]){inputRequests.push({type,touchPoints});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints});}const row={label,start:await snap()};assert(row.start.input.stick.x>.5&&row.start.input.stick.y<-.7);flow.retreat.push(row);}
 async function retreatEnd(){inputRequests.push({type:'touchEnd',touchPoints:[]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const row=flow.retreat.at(-1);row.end=await snap();assert.equal(row.end.input.stick.x,0);assert.equal(row.end.input.stick.y,0);row.horizontalDisplacement=Math.hypot(row.end.player.pelvis.x-row.start.player.pelvis.x,row.end.player.pelvis.z-row.start.player.pelvis.z);}
 await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.sound.ctx?.state==='running',null,45000);flow.start=await snap();assert.equal(flow.start.player.weapon,'pistol');assert.equal(flow.start.player.gun.ammo,6);await page.evaluate(()=>revolverProbe.watchAudio());
 flow.early=[];assert(flow.start.feetHeld&&flow.start.fightT<1);
 for(let i=0;i<3;i++){await page.touchscreen.tap(675,230);await page.waitForTimeout(100);const s=await snap();assert(s.feetHeld);assert.equal(s.player.gun.shots,0);assert.equal(s.player.gun.ammo,6);assert.equal(s.player.gun.pending,-1);flow.early.push(s);}
 await pause();flow.openingPause=await snap();await page.waitForTimeout(350);flow.openingPauseLater=await snap();assert.equal(flow.openingPauseLater.fightT,flow.openingPause.fightT);assert.equal(flow.openingPauseLater.player.gun.shots,0);await page.locator('#btnResume').tap();
 await waitFor(()=>game.player.fightT>=2.05,null,45000);flow.holdReleased=await snap();assert(!flow.holdReleased.feetHeld);assert.equal(flow.holdReleased.player.gun.shots,0);assert.equal(flow.holdReleased.player.gun.pending,-1);
 await page.touchscreen.tap(675,230);await waitFor(()=>revolverProbe.shotCalls.length===1&&game.player.gun.shots===1,null,12000);flow.firstShot=await snap();assert.equal(flow.firstShot.player.gun.ammo,5);assert(flow.firstShot.fightT>=2);

 await waitFor(()=>game.player.gun.cool<=0&&revolverProbe.decoded.filter(d=>d.file).length===8||game.state!=='fight',null,60000);assert.equal((await snap()).state,'fight');await page.screenshot({path:path.join(out,'tremor-before-reload.png')});shots.push('tremor-before-reload.png');flow.fixture=await page.evaluate(()=>revolverProbe.fixture());await page.touchscreen.tap(675,230);await waitFor(()=>game.player.gun.shots===2&&game.player.gun.reloading,null,12000);flow.reloadStarted=await snap();assert.equal(flow.reloadStarted.player.gun.ammo,0);console.log(JSON.stringify({event:'native-reload-started',snapshot:flow.reloadStarted}));await retreatStart('before-pause');
 await waitFor(()=>game.player.gun.cool<5.5||game.state!=='fight',null,60000);assert.equal((await snap()).state,'fight','Original combat ended before reload pause');await retreatEnd();await pause();flow.paused=await snap();await page.waitForTimeout(800);flow.pausedLater=await snap();assert.equal(flow.pausedLater.steps,flow.paused.steps);assert.equal(flow.pausedLater.player.gun.cool,flow.paused.player.gun.cool);
 await page.locator('[data-setting="sound"]').tap();flow.muted=await snap();assert(!flow.muted.sound.on&&!flow.muted.settings.sound);await page.locator('[data-setting="sound"]').tap();flow.unmuted=await snap();assert(flow.unmuted.sound.on&&flow.unmuted.settings.sound);await page.locator('#btnResume').tap();await waitFor(()=>game.state==='fight');await retreatStart('after-resume');
 await waitFor(()=>!game.player.gun.reloading||game.state!=='fight',null,150000);flow.completed=await snap();assert.equal(flow.completed.state,'fight','Original combat ended before reload completion');assert.equal(flow.completed.player.gun.ammo,6);assert.equal(flow.completed.player.gun.reloading,false);assert.equal(flow.completed.player.gun.shots,2);await retreatEnd();assert(flow.retreat.every(r=>r.end.steps>r.start.steps&&r.horizontalDisplacement>.02));await pause();await page.screenshot({path:path.join(out,'reload-completed.png')});shots.push('reload-completed.png');
 flow.audio=await page.evaluate(async()=>{await Promise.all(revolverProbe.decodeTasks);return revolverProbe.export();});const recorded=flow.audio.events.filter(e=>e.sources.some(s=>s.recording?.file));flow.recordedEvents=recorded;assert.equal(recorded.length,8);const names=['open',...Array.from({length:6},(_,i)=>`insert${i+1}`),'close'];for(let i=0;i<8;i++){const e=recorded[i],gain=i===0?EXPECT.gains.open:i===7?EXPECT.gains.close:EXPECT.gains.insert;assert.equal(e.sources.length,1);assert.equal(e.sources[0].recording.file,`sfx/revolver/${names[i]}.wav`);assert.equal(e.sources[0].start.length,1);assert(Math.abs(e.gain-gain)<1e-9);assert(Math.abs(e.actualGain-gain)<1e-6);assert.equal(e.context,'running');}const openingTime=recorded[0].gunT,expectedTimes=EXPECT.insertTimes;for(let i=0;i<6;i++)assert(Math.abs(recorded[i+1].gunT-openingTime-expectedTimes[i])<.025);assert(Math.abs(recorded[7].gunT-openingTime-EXPECT.reload)<.025);assert(flow.completed.player.gun.t-openingTime<EXPECT.reload+.5);flow.observedInsertGaps=recorded.slice(2,7).map((e,i)=>e.gunT-recorded[i+1].gunT);assert(flow.observedInsertGaps.every(gap=>Math.abs(gap-EXPECT.insertGap)<.025));const shotEvents=flow.audio.events.filter(e=>e.shot);assert.equal(shotEvents.length,2);assert(Math.abs(shotEvents[0].cool-EXPECT.cooldown)<1e-9);assert(Math.abs(shotEvents[1].cool-EXPECT.reload)<1e-9);flow.observedShotCooldowns=shotEvents.map(e=>e.cool);
 flow.gunWoundObservation={exposed:flow.audio.wounds.length>0,rows:flow.audio.wounds,meaning:'Natural gun applyWound observations only; no forced injury. Exact 80J energy contract is separately covered by native verification.'};const aim=flow.audio.aim;flow.tremor={samples:aim.length,simSpan:aim.at(-1).simTime-aim[0].simTime,rsHMin:Math.min(...aim.map(x=>x.rsH)),rsHMax:Math.max(...aim.map(x=>x.rsH)),distinctTargets:new Set(aim.map(x=>JSON.stringify(x.rsB))).size,commandRayTorsoMax:Math.max(...aim.map(x=>x.commandRayTorsoDistance)),commandRaySafetyBound:EXPECT.aimRaySafetyBound,meaning:'Original skill.update gunPose output and physical muzzle observations. Private target point is unexposed. The .40m bound is a coarse browser safety check, not exact envelope geometry or human accuracy/comfort evidence.'};assert(aim.length>=25);assert(flow.tremor.distinctTargets>=5);assert(flow.tremor.rsHMax<=EXPECT.randomHoldMax+.00001);assert(flow.tremor.commandRayTorsoMax<=EXPECT.aimRaySafetyBound);
 await page.evaluate(()=>{revolverProbe.oldPlayer=game.player;revolverProbe.oldWorld=game.world;revolverProbe.round=2;});await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.player!==revolverProbe.oldPlayer,null,45000);flow.restart=await snap();assert.equal(flow.restart.player.gun.ammo,6);assert.equal(flow.restart.player.gun.reloading,false);assert.equal(flow.restart.player.gun.shots,0);assert.equal(flow.restart.player.wounds,0);assert(await page.evaluate(()=>game.world!==revolverProbe.oldWorld));await page.touchscreen.tap(675,230);await page.waitForTimeout(100);flow.restartEarly=await snap();assert(flow.restartEarly.feetHeld);assert.equal(flow.restartEarly.player.gun.shots,0);assert.equal(flow.restartEarly.player.gun.ammo,6);await pause();episode=await page.evaluate(()=>revolverProbe.export());
 Object.assign(checks,{openingTapsRejected:flow.early.length===3&&flow.early.every(s=>s.player.gun.shots===0&&s.player.gun.ammo===6),openingPauseFrozen:flow.openingPauseLater.fightT===flow.openingPause.fightT,noOpeningQueuedShot:flow.holdReleased.player.gun.shots===0,restartOpeningGate:flow.restartEarly.player.gun.shots===0,trustedRetreat:flow.retreat.length===2&&flow.retreat.every(r=>r.horizontalDisplacement>.02),twoNativeShots:episode.shotCalls.length===2,eightRecordedEvents:true,eightWavDecoded:episode.decoded.length===8,eightWavDelivered:compiled.filter(x=>x.name.startsWith('dist/sfx/revolver/')).length===8,cooldownEightTenths:true,sixInsertsEightSecondScheduler:true,insertGapTwentyPercentShorter:true,pauseStopsScheduler:true,muteAndResume:true,restartFresh:true,tremorObserved:true,native:episode.native.length>0&&episode.native.every(e=>e.trusted&&e.kind==='touch'),finite:episode.nonfinite===0,oneExplicitAmmoFixture:episode.fixtures.length===1,preferencesRestored:episode.final.saved===settingsBytes,compiledExact:compiled.some(x=>x.name.startsWith('dist/assets/main-'))&&compiled.every(x=>x.match)});assert(Object.values(checks).every(Boolean));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page)episode=await page.evaluate(()=>revolverProbe?.export()??null);}catch{}}
finally{closingNormally=true;if(cdp)await cdp.detach().catch(()=>{});if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable&&errors.length===0&&performance.now()-startedWall<=300000;if(!pass)process.exitCode=1;const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),wallMs:performance.now()-startedWall,entryURL:entryURL.href,contract:EXPECT,settings:seeds,checks,flow,episode,compiled,lifecycle,errors,fatal,clockLimits,inputRequests,shots,tlsVerification:true,limits:['Three rejected opening taps plus two real trusted pistol shots; between the accepted shots explicit player.gun.ammo=1 fixture makes the second tap enter the original empty-cylinder path. Not six naturally fired rounds.','Original AI, damage, RNG, RAF/physics and audio function results retained. The probe does not accelerate the game clock. No seed search or forced survival. Native backward/strafe joystick input is held during reload, released for Pause and reapplied after Resume; the earlier stationary failure is preserved in the prior tuning receipt.','Delivered WAV hashes are linked through actual decodeAudioData output buffers to Sound.event sources that called native start. This proves original Web Audio scheduling, not physical-speaker output or human preference.','Aim samples are original gunPose outputs and physical muzzle readings, not private gunAimTarget coordinates. Exact 1.1 target-envelope geometry is outside this browser check and belongs to the independent native tests; the .40m browser ray bound is only a coarse safety check. Human shooting comfort is not inferred from these samples.']};await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,checks,errors,fatal,out}));}
