// Native mobile revolver aiming/shots with read-only original skill outputs and physical muzzle samples. No fixtures.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const own='tools/browser/revolver_aim_20261008.mjs';
const args={};for(const value of process.argv.slice(2)){const m=/^--(out|base)=(.+)$/.exec(value);assert(m&&!Object.hasOwn(args,m[1]));args[m[1]]=m[2];}
const artifactRoot='/workspace/halfsword-handoff/revolver-aim-20261008/browser';
assert(args.out);const out=path.resolve(args.out);assert(out.startsWith(artifactRoot+'/'));
await fs.mkdir(artifactRoot,{recursive:true});assert.equal(await fs.realpath(artifactRoot),artifactRoot);
assert.equal(path.dirname(out),artifactRoot,'Use one fresh direct child of the browser artifact root');await fs.mkdir(out);
const base=new URL(args.base||'https://yoonjl-svg.github.io/halfsword-codex/');
const local=['localhost','127.0.0.1','[::1]'].includes(base.hostname);
assert(!base.username&&!base.password&&!base.search&&!base.hash&&base.pathname.endsWith('/'));
assert(local&&['http:','https:'].includes(base.protocol)||base.href==='https://yoonjl-svg.github.io/halfsword-codex/');
const sha=x=>createHash('sha256').update(x).digest('hex');
async function scan(dir){const out=[];for(const e of(await fs.readdir(path.join(root,dir),{withFileTypes:true})).sort((a,b)=>a.name.localeCompare(b.name))){assert(!e.isSymbolicLink());const n=dir+'/'+e.name;if(e.isDirectory())out.push(...await scan(n));else if(e.isFile())out.push(n);}return out;}
const files=[...(await scan('src')).filter(x=>x.endsWith('.js')),own,'index.html','public/feature-lab.html','package.json','package-lock.json',...await scan('dist')].sort();
async function manifest(){return Object.fromEntries(await Promise.all(files.map(async n=>{const b=await fs.readFile(path.join(root,n));return[n,{bytes:b.length,sha256:sha(b)}];})));}
const before=await manifest(),head=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();
const startedUTC=new Date().toISOString(), startedWall=performance.now(), wallDeadline=startedWall+180000;await fs.writeFile(path.join(out,'manifest-before.json'),JSON.stringify({head,files:before},null,2)+'\n',{flag:'wx'});
const seeds={difficulty:'normal',pixel:false,blood:true,sound:true,invertTilt:false,moveMode:'stick',skill:'0.7',guardNames:true,trail:false,fpsCap:false};
const settingsBytes=JSON.stringify(seeds),errors=[],requests=[],compiled=[],fileChecks=[],inputRequests=[],shots=[],lifecycle=[];
const launch={executablePath:'/usr/bin/chromium',args:['--no-sandbox','--disable-background-networking','--use-gl=angle','--use-angle=swiftshader']};
const secrets=[];if(!local){const raw=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.HTTP_PROXY||process.env.http_proxy;assert(raw);const p=new URL(raw);launch.proxy={server:p.protocol+'//'+p.host};if(p.username)launch.proxy.username=decodeURIComponent(p.username);if(p.password)launch.proxy.password=decodeURIComponent(p.password);secrets.push(raw,p.username,p.password,launch.proxy.username,launch.proxy.password);}
const clean=x=>{let s=String(x);for(const v of secrets.filter(Boolean))s=s.split(v).join('[redacted]');return s.replace(/https?:\/\/[^\s/@:]+:[^\s/@]+@/gi,'https://[redacted]@').slice(0,5000);};
const confined=value=>{try{const u=new URL(value);if(u.protocol==='data:')return true;if(u.protocol==='blob:')return new URL(u.pathname).origin===base.origin;const p=decodeURIComponent(u.pathname);return!u.username&&!u.password&&u.origin===base.origin&&u.pathname.startsWith(base.pathname)&&p.startsWith(decodeURIComponent(base.pathname))&&!p.includes('\\')&&!p.split('/').some(x=>x==='..'||x==='.');}catch{return false;}};
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'/workspace/cloud-onboarding/browser/node_modules/playwright/index.mjs');
let browser,context,page,cdp,fatal=null,episode=null,pass=false,closingNormally=false;
const flow={},checks={},clockLimits=[];const entryURL=new URL('?weapon=pistol&foe=heinrich&foeWeapon=longsword',base);
await fs.copyFile(path.join(root,own),path.join(out,'executed-tool.mjs'));
const remaining=()=>wallDeadline-performance.now();
async function waitFor(fn,arg,maximum=15000){const timeout=Math.max(100,Math.min(maximum,remaining()-1500));try{return await page.waitForFunction(fn,arg,{timeout});}catch(e){if(e.name==='TimeoutError')clockLimits.push({wallMs:performance.now()-startedWall,maximum,remaining:remaining()});throw e;}}
try{
 browser=await chromium.launch(launch);context=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,ignoreHTTPSErrors:false,serviceWorkers:'block'});context.setDefaultTimeout(15000);
 await context.addInitScript(bytes=>localStorage.setItem('gladiator-settings',bytes),settingsBytes);
 await context.route('**/*',async route=>{const url=route.request().url();if(!confined(url)){errors.push({kind:'blocked',url:clean(url)});await route.abort('blockedbyclient');return;}try{const r=await route.fetch({maxRedirects:0,maxRetries:2});if(r.status()>=300&&r.status()<400){errors.push({kind:'redirect',url:clean(url),status:r.status()});await route.abort('blockedbyclient');return;}const relative=new URL(url).pathname.slice(base.pathname.length);if(!relative||relative==='development-plan.html'||relative.startsWith('assets/')&&relative.endsWith('.js')){const body=await r.body(),name='dist/'+(relative||'index.html'),wanted=before[name],digest=sha(body);compiled.push({name,url:clean(url),bytes:body.length,sha256:digest,match:!!wanted&&body.length===wanted.bytes&&digest===wanted.sha256,capture:'route.fetch APIResponse',delivery:'identical body passed to route.fulfill'});await route.fulfill({response:r,body});}else await route.fulfill({response:r});}catch(e){errors.push({kind:'route',url:clean(url),message:clean(e.message)});await route.abort('failed');}});
 if(context.routeWebSocket)await context.routeWebSocket('**/*',s=>{errors.push({kind:'websocket',url:clean(s.url())});s.close();});
 page=await context.newPage();page.on('pageerror',e=>errors.push({kind:'pageerror',message:clean(e.message)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:clean(m.text())});});page.on('requestfailed',r=>errors.push({kind:'requestfailed',url:clean(r.url()),message:clean(r.failure()?.errorText)}));
 page.on('response',r=>{if(r.status()>=400)errors.push({kind:'http',url:clean(r.url()),status:r.status()});});
 const life=(event,url)=>lifecycle.push({event,url:clean(url),wallMs:performance.now()-startedWall,closingNormally});page.on('crash',()=>{life('page-crash',page.url());errors.push({kind:'page-crash',url:clean(page.url())});});page.on('close',()=>{life('page-close',page.url());if(!closingNormally)errors.push({kind:'unexpected-page-close',url:clean(page.url())});});page.on('worker',worker=>{life('worker-open',worker.url());worker.on('close',()=>life('worker-close',worker.url()));});
 await page.goto(entryURL.href,{waitUntil:'load',timeout:30000});await waitFor(()=>window.game?.ai&&game?.combat&&game?.swordsmanshipDefault);cdp=await context.newCDPSession(page);
 await page.evaluate(()=>{
  const p=window.aimProbe={round:1,steps:0,aiCalls:0,skillUpdates:0,samples:[],native:[],shots:[],wounds:[],nonfinite:0};const vec=v=>({x:v.x,y:v.y,z:v.z});
  const gun=f=>f.gun?Object.fromEntries(['cool','pending','shots','hits','ammo','reloading','t','h','since','what'].map(k=>[k,typeof f.gun[k]==='object'?{...f.gun[k]}:f.gun[k]])):null;
  p.read=()=>({round:p.round,state:game.state,simTime:game.stats.simTime,steps:p.steps,aiCalls:p.aiCalls,player:{name:game.player.name,alive:game.player.alive,state:game.player.state,armed:game.player.armed,weapon:game.player.weapon.id,fightT:game.player.fightT,wounds:game.player.wounds.length,pelvis:vec(game.player.bodies.pelvis.translation()),gun:gun(game.player)},enemy:{name:game.enemy.name,alive:game.enemy.alive,weapon:game.enemy.weapon.id},sound:{on:game.sound.on,context:game.sound.ctx?.state},settings:{...game.settings},saved:localStorage.getItem('gladiator-settings'),default:{...game.swordsmanshipDefault},policies:{gravity:game.world.gravity.y,finish:game.combat.finishRuleModel,limb:game.config.COMBAT.limbSeverTrial},input:{activeTouch:game.input.activeTouch,pending:[game.input.handDX,game.input.handDY],taps:game.input.taps,stick:{...game.input.stickMove},move:{...game.input.move}}});
  const sp=Object.getPrototypeOf(game.player.skill),skillUpdate=sp.update;sp.update=function(...args){const ret=skillUpdate.apply(this,args);if(this===game.player.skill){p.skillUpdates++;if(p.skillUpdates%12===0&&p.samples.length<100){const f=game.player,g=f.gun,T=game.THREE,q=new T.Quaternion().copy(f.sword.rotation()),origin=f.bladePoint(1,new T.Vector3()).add(new T.Vector3(f.weapon.muzzleX??0,0,0).applyQuaternion(q)),muzzleDir=new T.Vector3(0,1,0).applyQuaternion(q),commandDir=new T.Vector3(...this.thrustPose.dir).applyQuaternion(f.yaw),commandOrigin=new T.Vector3(...this.thrustPose.hand).applyQuaternion(f.yaw).add(new T.Vector3().copy(f.bodies.chest.translation())),bodyLine=['pelvis','abdomen','chest',...(!f.foe.decapitated&&f.foe.bodies.head?['head']:[])].map(k=>new T.Vector3().copy(f.foe.bodies[k].translation())),ray=new T.Ray(commandOrigin,commandDir),rayTorsoDistance=Math.sqrt(Math.min(...bodyLine.slice(1).map((b,i)=>ray.distanceSqToSegment(bodyLine[i],b))));p.samples.push({round:p.round,simTime:game.stats.simTime,gunT:g?.t,h:g?.h,since:g?.since,cool:g?.cool,reloading:g?.reloading,standing:f.state==='stand'||f.state==='kneel',pose:{w:this.thrustPose.w,hand:[...this.thrustPose.hand],dir:[...this.thrustPose.dir]},commandDirWorld:vec(commandDir),commandRayOrigin:vec(commandOrigin),commandRayTorsoDistance:rayTorsoDistance,physicalMuzzle:{origin:vec(origin),dir:vec(muzzleDir)},foeBodies:Object.fromEntries(['pelvis','abdomen','chest','head'].filter(k=>f.foe.bodies[k]).map(k=>[k,vec(f.foe.bodies[k].translation())]))});}}return ret;};
  const cp=Object.getPrototypeOf(game.combat),after=cp.afterStep;cp.afterStep=function(...args){const ret=after.apply(this,args);if(this===game.combat){p.steps++;if(p.steps%30===0)for(const f of [game.player,game.enemy])if(![...Object.values(f.bodies),f.sword].every(b=>[b.translation(),b.rotation(),b.linvel(),b.angvel()].every(v=>Object.values(v).every(Number.isFinite))))p.nonfinite++;}return ret;};
  const ap=Object.getPrototypeOf(game.ai),update=ap.update;ap.update=function(...args){const ret=update.apply(this,args);if(this===game.ai)p.aiCalls++;return ret;};
  const fp=Object.getPrototypeOf(game.player),wound=fp.applyWound;fp.applyWound=function(h,...rest){const ret=wound.call(this,h,...rest);if(h.gun&&p.wounds.length<12)p.wounds.push({round:p.round,simTime:game.stats.simTime,victim:this.name,part:h.part,zone:h.zone,energy:h.energy,type:h.type,pass:h.pass,helmet:h.helmet});return ret;};
  const shot=game.sound.gunshot;game.sound.gunshot=function(...args){const ret=shot.apply(this,args);p.shots.push({round:p.round,simTime:game.stats.simTime,on:this.on,gun:gun(game.player)});return ret;};
  for(const type of ['pointerdown','pointermove','pointerup','pointercancel'])document.addEventListener(type,e=>{if(p.native.length<100)p.native.push({type,trusted:e.isTrusted,kind:e.pointerType,target:e.target.closest?.('button')?.id||e.target.id,round:p.round,simTime:game.stats.simTime});},true);
  p.export=()=>({steps:p.steps,aiCalls:p.aiCalls,skillUpdates:p.skillUpdates,samples:p.samples,native:p.native,shots:p.shots,wounds:p.wounds,nonfinite:p.nonfinite,final:p.read()});
 });
 const snap=()=>page.evaluate(()=>aimProbe.read());const pause=async()=>{await page.locator('#btnPause').tap();await waitFor(()=>game.state==='paused');};const shot=async name=>{await page.screenshot({path:path.join(out,name+'.png')});shots.push(name+'.png');};
 await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.sound.ctx?.state==='running',null,45000);flow.start=await snap();assert.equal(flow.start.player.weapon,'pistol');assert.equal(flow.start.enemy.weapon,'longsword');assert.equal(flow.start.player.gun.ammo,6);
 await page.touchscreen.tap(675,230);await waitFor(()=>aimProbe.shots.length===1&&game.player.gun.shots===1,null,12000);flow.firstShot=await snap();assert.equal(flow.firstShot.player.gun.ammo,5);console.log(JSON.stringify({event:'first-shot',snapshot:flow.firstShot}));
 await waitFor(()=>game.player.fightT>=2.2||game.state!=='fight',null,60000);assert.equal((await snap()).state,'fight');const box=await page.locator('#moveStick').boundingBox(),point={x:box.x+box.width/2,y:box.y+box.height/2,id:88};flow.beforeMove=await snap();for(const [type,touchPoints] of [['touchStart',[point]],['touchMove',[{...point,y:point.y+34}]]]){inputRequests.push({type,touchPoints});await cdp.send('Input.dispatchTouchEvent',{type,touchPoints});}flow.heldMove=await snap();assert(flow.heldMove.input.stick.y<-.5);await waitFor(n=>aimProbe.steps>=n,flow.heldMove.steps+60,15000);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});inputRequests.push({type:'touchEnd',touchPoints:[]});flow.afterMove=await snap();assert.equal(flow.afterMove.input.stick.y,0);await shot('aim-after-movement');
 await pause();flow.paused=await snap();await page.waitForTimeout(600);flow.pausedLater=await snap();assert.equal(flow.pausedLater.steps,flow.paused.steps);await page.locator('#btnResume').tap();await waitFor(()=>game.state==='fight');await waitFor(()=>game.player.fightT>=4||game.state!=='fight',null,45000);assert.equal((await snap()).state,'fight');await shot('aim-before-restart');await pause();flow.beforeRestart=await snap();
 await page.evaluate(()=>{aimProbe.oldPlayer=game.player;aimProbe.oldWorld=game.world;aimProbe.round=2;});await page.locator('#btnStart').tap();await waitFor(()=>game.state==='fight'&&game.player.gun&&game.player!==aimProbe.oldPlayer,null,45000);flow.restart=await snap();assert.equal(flow.restart.player.gun.ammo,6);assert.equal(flow.restart.player.gun.shots,0);assert.equal(flow.restart.player.wounds,0);assert(await page.evaluate(()=>game.world!==aimProbe.oldWorld));await page.touchscreen.tap(675,230);await waitFor(()=>aimProbe.shots.length===2&&game.player.gun.shots===1,null,12000);flow.secondShot=await snap();await pause();episode=await page.evaluate(()=>aimProbe.export());
 const stable=episode.samples.filter(s=>s.round===1&&s.standing&&s.pose.w===1&&!s.reloading&&s.since>.25),heights=stable.map(s=>s.h);flow.aimObservation={privateTargetPoint:'Not exposed. Samples are original skill.update→gunPose output and physical muzzle, not a rerun of gunAimTarget.',stableSamples:stable.length,hMin:Math.min(...heights),hMax:Math.max(...heights),commandRayTorsoDistanceMax:Math.max(...stable.map(s=>s.commandRayTorsoDistance)),commandRayMeaning:'Distance from the original gunPose output ray to simultaneously observed pelvis-abdomen-chest-attached-head segments; not private target coordinates or bullet impact.',physicalMuzzleAndCommandDistinct:true};assert(stable.length>=10);assert(flow.aimObservation.hMax-flow.aimObservation.hMin>.05);assert(flow.aimObservation.commandRayTorsoDistanceMax<=.301);
 Object.assign(checks,{twoNativeShots:episode.shots.length===2,moveAndRelease:true,pauseResume:true,freshRestart:true,originalAimOutputObserved:true,finite:episode.nonfinite===0,native:episode.native.length>0&&episode.native.every(x=>x.trusted&&x.kind==='touch'),preferences:episode.final.saved===settingsBytes,compiledExact:compiled.some(x=>x.name.startsWith('dist/assets/main-'))&&compiled.every(x=>x.match)});assert(Object.values(checks).every(Boolean));assert.deepEqual(errors,[]);pass=true;
}catch(e){fatal={name:e.name,message:clean(e.message),stack:clean(e.stack)};process.exitCode=1;try{if(page)episode=await page.evaluate(()=>aimProbe?.export()??null);}catch{}}
finally{closingNormally=true;if(cdp)await cdp.detach().catch(()=>{});if(context)await context.close();if(browser)await browser.close();const after=await manifest(),headAfter=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),sourceStable=JSON.stringify(before)===JSON.stringify(after)&&head===headAfter;pass=pass&&sourceStable&&errors.length===0&&performance.now()-startedWall<=180000;if(!pass)process.exitCode=1;const report={pass,sourceStable,head,headAfter,startedUTC,completedUTC:new Date().toISOString(),wallMs:performance.now()-startedWall,entryURL:entryURL.href,settings:seeds,checks,flow,episode,compiled,lifecycle,errors,fatal,clockLimits,inputRequests,shots,tlsVerification:true,limits:['No state, injury, ammunition, RNG, pose or clock injection. Two trusted pistol taps across a restart; original AI and real RAF physics.','Private gunAimTarget output is not exposed. Observe original skill.update gunPose command outputs and actual physics muzzle separately; recoil and bullet spread remain separate.','75J configuration delivery is established through matching compiled/source bytes plus independent native source tests. Natural gun wounds are recorded only if exposed, not forced.','A short body-height wander sample and screenshots do not guarantee torso impacts, universal aiming accuracy, or human comfort. No new audio offline rendering or reload fixture.']};await fs.writeFile(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({pass,sourceStable,checks,errors,fatal,out}));}
