// ─────────────────────────────────────────────────────────────
//  출처 목록 (동작 연구 PM). 클립 JSON 의 sources 칸이 이 id 를 가리킨다.
//  kind: manual(교본 원문·도판) · translation(번역·해설) · mocap(모션 캡처 논문) · dataset(공개 데이터) · biomech(스포츠 생체역학) · estimate(추정)
//  read: 우리가 실제로 읽은 깊이 — 'snippet'(검색 요약), 'abstract'(초록), 'full'(본문), 'memory'(확인 전 기억)
//  license: 이용 조건 (확인한 범위)
// ─────────────────────────────────────────────────────────────
export const SOURCES = {
  meyer_zornhut: {
    kind: 'translation',
    cite: 'Joachim Meyer, Gründtliche Beschreibung der Kunst des Fechtens (1570) 장검 3장 분노의 자세 (Garber 역 + 1570 독일어 본문 대조, 9/29)',
    quote: '"stand with your left foot forward, hold your sword at the right shoulder such that the blade hangs down behind you" (Garber 역)',
    url: 'https://sprechfenster.org/meyer/1570/longsword-chapter-3-the-guards/',
    read: 'full',
    license: '원문(1570) 퍼블릭 도메인. Garber 번역은 조건 확인 전 — 짧은 인용만'
  },
  meyer_zornhau: {
    kind: 'translation',
    cite: 'Meyer 1570 장검 4장(fol. Ⅰ.11r.5): Zornhau = 오른 어깨에서 상대 왼쪽 귀로, 또는 얼굴·가슴을 지나는 사선 베기. 3장(fol. Ⅰ.9v.3–10r.1): 분노의 자세에서 시작해 반쯤에 긴 자세, 끝에 바꿈(Wechsel) — Garber 역 + 독일어 원문 대조',
    url: 'https://sprechfenster.org/meyer/1570/longsword-chapter-4-the-cuts/',
    read: 'full',
    license: '원문 퍼블릭 도메인. 번역은 짧은 인용만',
  },
  meyer_master: {
    kind: 'translation',
    cite: 'Meyer 1570 장검 4장(fol. Ⅰ.11r.2): 다섯 비밀 베기(Zorn·Krump·Zwerch·Schieler·Scheitel) — 모든 참된 기술이 여기서 나온다. Schiel·Krump·Zwerch 는 분노의 자세·왼발 앞에서 오른발을 상대 왼쪽으로 크게 딛으며',
    url: 'https://sprechfenster.org/meyer/1570/longsword-chapter-4-the-cuts/',
    read: 'full',
    license: '원문 퍼블릭 도메인, 번역 저작권 있음',
  },
  meyer_step: {
    kind: 'translation',
    cite: 'Meyer 1570 장검 7장 걸음: "each strike must have its own step, which should occur simultaneously with the strike" — 너무 이르거나 늦으면 기술이 망가진다',
    url: 'https://sprechfenster.org/meyer/1570/longsword-chapter-7-steps/',
    read: 'full',
    license: '원문 퍼블릭 도메인. 번역은 짧은 인용만',
  },
  doebringer_step: {
    kind: 'translation',
    cite: 'Pseudo-Hans Döbringer (1389) 주해, David Lindholm 역 — "왼발을 앞에 두고 오른쪽에서 벨 때 오른발로 따라 내딛지 않으면 그 베기는 틀렸다"',
    url: 'https://wiktenauer.com/wiki/Pseudo-Hans_Döbringer/David_Lindholm_LS_2005',
    read: 'snippet',
    license: '원문 퍼블릭 도메인. 번역 이용 조건은 Wiktenauer 토론 페이지 표에 있음(미확인)',
  },
  ringeck_zornhau: {
    kind: 'translation',
    cite: 'Sigmund Ringeck 주해 27절, Christian Trosclair 역 — 상대가 오른쪽에서 위로 베어 오면 너도 오른 어깨에서 앞날로 세게 함께 벤다. 칼에 약하면 칼끝을 길게 얼굴로. (걸음은 이 절에 없다)',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck',
    read: 'full',
    license: '원문 퍼블릭 도메인. Trosclair 역은 CC BY-NC-SA 4.0(비영리) — 짧은 인용만, 게임 안 글로 옮기지 않는다',
  },
  zettel_verses: {
    kind: 'manual',
    cite: 'Liechtenauer Zettel (14세기) 다섯 베기 구절 — "Krump auf behende, wirf den Ort auf die Hände" · "Zwerch benimmt, was vom Tag dar kommt" · "Schieler bricht, was Büffel schlägt oder sticht" · "Der Scheitler mit seiner Kehr, dem Antlitz ist er gefähr"',
    url: 'https://wiktenauer.com/wiki/Johannes_Liechtenauer',
    read: 'memory',
    license: '퍼블릭 도메인',
  },
  gloss_zwerch: {
    kind: 'translation',
    cite: 'Ringeck 주해 49절(Trosclair 역) — Zwerchhau: 오른발로 상대 왼쪽으로 뛰어 딛으며, 칼자루를 머리 앞 높이 들고 엄지를 아래로 대어 뒷날로 상대 왼쪽을 가로 벤다. 위에서 오는 베기·지붕 자세를 깬다',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck',
    read: 'full',
    license: '원문 퍼블릭 도메인. Trosclair 역 CC BY-NC-SA 4.0(비영리)',
  },
  gloss_schiel: {
    kind: 'translation',
    cite: 'Ringeck 주해 58~59절(Trosclair 역) — Schielhau: 오른쪽에서 팔을 곧게 뻗어 뒷날로 상대 칼의 약한 곳을 쳐 오른 어깨를 벤다. 바꿔 빠지면 길게 가슴으로. 쟁기·아래 찌르기를 깬다',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck',
    read: 'full',
    license: '원문 퍼블릭 도메인. Trosclair 역 CC BY-NC-SA 4.0(비영리)',
  },
  gloss_scheitel: {
    kind: 'translation',
    cite: 'Ringeck 주해 63절(Trosclair 역) — Scheitelhau: 얼굴과 가슴 둘 다를 위협한다. 바보 자세에 맞서 위에서 곧게 앞날로 내려 베고, 팔을 높이 둔 채 칼끝을 얼굴로 늘어뜨린다',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck',
    read: 'full',
    license: '원문 퍼블릭 도메인. Trosclair 역 CC BY-NC-SA 4.0(비영리)',
  },
  gloss_krump: {
    kind: 'translation',
    cite: 'Ringeck 주해 42절(Trosclair 역) — Krumphau: 상대 베기에서 오른발로 상대 왼쪽까지 넓게 뛰어 비키며, 팔을 엇걸어 칼끝을 상대 손 위로 친다. 황소 자세에도 쓴다',
    url: 'https://wiktenauer.com/wiki/Sigmund_ain_Ringeck',
    read: 'full',
    license: '원문 퍼블릭 도메인. Trosclair 역 CC BY-NC-SA 4.0(비영리)',
  },
  meyer_diagram: {
    kind: 'manual',
    cite: 'Meyer 1570 베기 그림 — 세로(Scheitel)·가로(Mittel/Zwerch)·사선 두 줄(Ober·Unter / Zorn) 선의 네모·십자 도형',
    url: 'https://grauenwolf.wordpress.com/2015/11/29/meyers-rapierannotated-cutting-diagrams/',
    read: 'snippet',
    license: '원문 도판 퍼블릭 도메인',
  },
  golf_sequence: {
    kind: 'biomech',
    cite: 'Cheetham 외 2008 (골프 프로 vs 아마추어 운동 사슬): 프로는 골반 → 가슴 → 팔 → 채 순서로 최고 각속도, 팔→채 간격이 골반→팔 간격의 2배 이상. 골반 480±82, 가슴 605±87, 앞팔 1310±236 °/s (다른 연구)',
    url: 'https://www.researchgate.net/publication/252236426',
    read: 'snippet',
    license: '논문 수치 인용',
  },
  golf_xfactor: {
    kind: 'biomech',
    cite: 'TPI 예시: 어깨 90° · 골반 50° → X-factor 40°. Cheetham 2001 X-factor stretch: 내려치기 시작 때 숙련자는 X-factor 를 19% 더 벌린다',
    url: 'https://www.mytpi.com/articles/biomechanics/the-difference-between-x-factor-and-x-factor-stretch',
    read: 'snippet',
    license: '인용',
  },
  baseball_sequence: {
    kind: 'biomech',
    cite: 'Welch 외 1995 JOSPT 22(5) 야구 타격: 골반 최고 714 °/s → 어깨 937 °/s. Escamilla 외 2009 (J. Appl. Biomech. 25(3)): 성인 윗몸 857 °/s, 배트 30 m/s (청소년 717 °/s·25 m/s, 연구 ASS 표본 점검 9/29 확인)',
    url: 'https://www.jospt.org/doi/10.2519/jospt.1995.22.5.193',
    read: 'snippet',
    license: '인용',
  },
  swordstem_speed: {
    kind: 'biomech',
    cite: 'SwordSTEM (Sean Franklin) "How fast do swords move": 힘 뺀 오른쪽 내려베기, 베는 부분 최고 약 20 m/s, 닿기 몇 인치 앞에서 최고',
    url: 'https://swordstem.com/2018/08/22/how-fast-do-swords-move-try-1/',
    read: 'snippet',
    license: '인용',
  },
  arma_speed: {
    kind: 'estimate',
    cite: 'George Turner (ARMA) "Sword Motions and Impacts" 3부: 칼자루(탱) 힘을 셈하는 가정 예시 — "75 mph 로 부딪히면 폼멜 빠르기가 15 mph 넘게 바뀌어야". 측정값이 아니다 (9/29 밤 1~3부 본문으로 확인). 칼끝 빠르기 근거로 쓰지 않는다',
    url: 'https://thearma.org/spotlight/GTA/motions_and_impacts3.htm',
    read: 'full',
    license: '인용',
  },
  aaos_rom: {
    kind: 'biomech',
    cite: 'AAOS 관절 가동 범위 (1965, Greene & Heckman 1994): 어깨 굽힘·벌림 180°, 팔꿈치 150°, 손목 굽힘 80°·폄 70°, 가슴허리 돌림 45°, 엉덩이 안쪽·바깥 돌림 45°',
    url: 'https://link.springer.com/article/10.1186/s12891-020-03665-9',
    read: 'snippet',
    license: '인용',
  },
  mocap_5mudm: {
    kind: 'mocap',
    cite: 'Klempous 외 2021 IEEE CINTI pp.137–142 (doi 10.1109/CINTI53070.2021.9668598) / Kluwak 외 2022 EUROCAST LNCS 13789 pp.504–511 — 독일 롱소드 다섯 비밀 베기 모캡: 숙련자 1명 + 초보들(수 미상), 전신 Plug-in Gait 39 마커, 근전도 16, 힘·영상 (초록으로 확인 9/29 밤). 기관(PJAIT HML)·Vicon 은 초록에 없음',
    url: 'https://doi.org/10.1007/978-3-031-25312-6_59',
    read: 'abstract',
    license: '공개 자료 없음(Zenodo·Figshare·OpenAlex 찾아봄). 접근 조건은 초록에 없다. 요청(저자·기관 연락)은 사장님 허락 뒤 — 사장님 답(9/29): 하지 않음',
  },
  mocap_sose2020: {
    kind: 'mocap',
    cite: 'Grontman 외, "Analysis of sword fencing training evaluation possibilities using Motion Capture techniques", IEEE SoSE 2020 — Zwerchhau·Schielhau 칼끝 마커 궤적 그림, 4명(전문 1)',
    url: 'https://ieeexplore.ieee.org/document/9130469/',
    read: 'abstract',
    license: '논문 — 그림 수치 인용만',
  },
  cmu_02: {
    kind: 'dataset',
    cite: 'CMU Graphics Lab Motion Capture, subject 02 trial 07·08·09 "swordplay" (120 Hz)',
    url: 'http://mocap.cs.cmu.edu/',
    read: 'snippet',
    license: '연구·상업 제품 포함 사용 가능, 데이터 자체 재판매 금지(변환본 포함), 출처 표기 요청. 유파 검술 아님',
  },
  fencing_review: {
    kind: 'biomech',
    cite: 'Chen 외 2017 "Biomechanics of fencing sport: A scoping review" (PLoS ONE 12(2) e0171578): 숙련자는 칼 든 팔을 앞발보다 먼저 뻗는다(Hassan & Klauck 1998 인용). 런지 최고 빠르기 무게중심 1.92/1.72 m/s, 칼 2.91/2.49, 앞발 4.56/4.10 (9/29 본문 확인)',
    url: 'https://doi.org/10.1371/journal.pone.0171578',
    read: 'full',
    license: '인용 (CC BY)',
  },
  fencing_gholipour: {
    kind: 'biomech',
    cite: 'Gholipour·Tabrizi·Farahmand 2008 "Kinematics analysis of lunge fencing using stereophotogrametry", World J. Sport Sci. 1(1):32–37 — 남자 플뢰레 8명(샤리프대 초보 4·국가대표 4), 50 fps 카메라 3대, 옆면 2D. 팔꿈치가 무릎보다 먼저 움직이기 시작: 초보 0.13±0.15 s, 숙련 0.07±0.05 s — 저자는 숙련자가 팔·다리를 "거의 함께" 움직인다고 읽고 "손 먼저" 믿음을 반박한다. 엉덩관절 굽힘 숙련 53±11° / 초보 40±7°, 앞무릎 처음 굽힘 20±12° → 폄 51±9° (초보 38 → 18±8°)',
    url: 'https://clasicalfencing.wordpress.com/2017/07/21/',
    read: 'full',
    license: '인용 (본문은 블로그 전재본으로 읽음 — 출판사 idosi.org 는 자동 접속 거절)',
  },
  fencing_mulloy: {
    kind: 'biomech',
    cite: 'Mulloy 외 ISBS "Use of the kinematic chain in the fencing attacking lunge": 숙련자 뒷다리 엉덩이→무릎→발목 순서(초보는 뚜렷하지 않음), 뒷발목 폄 564±132 °/s (초보 273±184). Mulloy·Mullineaux·Irwin 2015 ISBS 33, pp.1114–1117, 숙련 4·초보 6, 카메라 12대',
    url: 'https://ojs.ub.uni-konstanz.de/cpa/article/view/6606',
    read: 'full',
    license: '인용',
  },
  fencing_lunge: {
    kind: 'biomech',
    cite: 'ISBS 엘리트 펜싱 런지: 길이 1.24 m (0.88~1.86), 엉덩이 속도 1.97 m/s, 몸통 앞기울기 17.5°',
    url: 'https://ojs.ub.uni-konstanz.de/cpa/article/view/3742',
    read: 'snippet',
    license: '인용',
  },
  kendo_men: {
    kind: 'biomech',
    cite: '검도 머리치기: 8단 10명 모캡(Murase 외 ISBS 2020, 수치는 초록에 없음). 대학 선수 머리치기 총 0.818±0.085 s · 손목치기 0.745±0.101 s (Sports Biomechanics 2026 — 19명, 동작 시작~닿기 직전, 250 Hz, 연구 ASS 표본 점검 9/29 확인)',
    url: 'https://commons.nmu.edu/isbs/vol38/iss1/135/',
    read: 'abstract',
    license: '인용',
  },
  figueyredo_montante: {
    kind: 'translation',
    cite: 'Diogo Gomes de Figueyredo, Memorial of the Practice of the Montante (1651) — 몬탄테 혼자 연습 규칙 32개(단순 16 + 겹친 16): 걸음마다 아래에서 위로 올려베기·머리 위로 넘겨 돌리는 베기를 잇고, 몸은 칼이 베는 쪽으로 돈다. 베기마다 칼을 얼굴 앞에 세워 멈춘다(Rule I 외)',
    url: 'https://wiktenauer.com/wiki/Diogo_Gomes_de_Figueyredo',
    read: 'full',
    license: '원문(1651) 퍼블릭 도메인. Myers·Hick 역은 CC BY-NC-SA 4.0(비영리) — 서술만 요약',
  },
  moulinet_manuals: {
    kind: 'manual',
    cite: 'Burton, A New System of Sword Exercise for Infantry (1876) II장 §2 The Moulinet: 손을 뒤집으며 칼이 오른 어깨 옆을 지나 원을 그린다(Outside Moulinet), 팔은 거의 편 채 팔꿈치가 흔들리지 않게. Allanson-Winn & Phillipps-Wolley, Broad-Sword and Single-Stick (1890) III장: 원 막기에서 손목을 오른 어깨 20~25 cm 까지 당기고 칼끝을 뒤로 떨궈 원을 그린다; 베기는 이어 휘두른다',
    url: 'https://www.gutenberg.org/ebooks/59336',
    read: 'full',
    license: '원문 퍼블릭 도메인(1876·1890, Project Gutenberg)',
  },
  tennis_upper_limb: {
    kind: 'biomech',
    cite: '테니스 포핸드(엘리트, IMU): 라켓 빠르기 중 위팔 수평 굽힘 45~48%, 팔꿈치 폄 17~21%, 위팔 안쪽 돌림 14~16% (Sensors 2022 "Upper limb joint contribution … IMU")',
    url: 'https://www.mdpi.com/journal/sensors',
    read: 'snippet',
    license: '인용',
  },
  meyer_dussack: {
    kind: 'translation',
    cite: 'Meyer 1570 뒤삭(한손 칼) 3장 네 베기: 황소에서 딛으며 곧게 내려 벤 뒤 팔을 뻗은 긴 자세에서 멈추고, 칼 앞쪽을 왼쪽 아래로 떨어뜨리며 칼자루를 칼이 늘어진 채 머리 둘레로 끌어올려 다시 벤다 — 베기마다 오른발을 앞으로. 첫째 규칙은 "처음엔 반만(긴 자세까지), 둘째엔 선을 끝까지 지나" 벤다 (fol. Ⅱ.4v, Garber 역 + 1570 원본 영인본)',
    url: 'https://sprechfenster.org/meyer/1570/dusack-chapter-3-the-four-cuts/',
    read: 'full',
    license: '원문 퍼블릭 도메인. 번역은 짧은 인용만',
  },
  heavy_implement: {
    kind: 'biomech',
    cite: '무거운 도구의 운동 사슬: Gutiérrez-Dávila·Rojas·Campos 2009 회전 투포환 마지막 동작(Motricidad 22:31–46, 2008 세계실내 결승 6명) — 앞 60% 는 발목·무릎·엉덩이가 함께 펴는 밀기, 그 뒤 팔꿈치(60%에서 시작, 85%에서 최고)·손목 차례. 두 마디 팔 모형은 가벼운·무거운 도구의 최적 기법이 다르다고 봄(Alexander 1991 J Theor Biol 계열)',
    url: 'https://eurjhm.com/index.php/eurjhm/article/view/217',
    read: 'full',
    license: '인용',
  },
  game_weapons: {
    kind: 'estimate',
    cite: '게임 무기 스펙 src/weapons.js (츠바이핸더: Albion "The Wallace" 2.892 kg·칼날 1.17 m 실측 + 균형점 추정) — 손 자리·칼 길이·무게·앞손 둘레 관성을 여기서 읽음 (tools/motion/lib/weapons.mjs)',
    url: '',
    read: 'full',
    license: '우리 것',
  },
  estimate: {
    kind: 'estimate',
    cite: '동작 연구 PM 추정 — 게임 뼈대 치수·교본 자세·생체역학 범위 안에서 정함',
    url: '',
    read: 'full',
    license: '우리 것',
  },
};
