// Independent encounters. Existing campaign order and random roster stay explicit in characters.js.
// Biographies are fiction; personas reuse the game's weapon schools, not historical motion captures.
import { getLook, CHARACTER_LOOK_VERSION } from './looks.js';

export const EXPANSION_CHARACTERS = [
  {
    id: 'artoria', name: '아르토리아', epithet: '돌아온 맹세', age: 24,
    origin: '브리튼 · 바다 너머의 잃어버린 왕국', weapon: 'excalibur', voice: 'isolde',
    backstory: '금빛 검을 지녔다는 소문을 따라 바다를 건넌 기사. 왕관도 군대도 없이 돌아왔지만, 엑스칼리버는 여전히 그녀의 손에서 빛난다. 이름을 빌린 이들을 벌하기보다, 그 이름이 지켜야 했던 사람들을 찾는다.',
    want: '검에 걸었던 맹세를 끝까지 지키고, 흩어진 사람들을 고향으로 돌려보내는 것.',
    school: '엑스칼리버의 실제 소유자라는 게임 속 창작 설정. 기존 양손검 자세와 엑스칼리버 유파를 사용한다.',
    signatureMoves: '몸 가까이 검을 되찾고, 짧은 준비에서 크게 비스듬히 벤다.',
    favoriteGuards: '오른쪽 어깨와 쟁기. 칼끝으로 길을 닫고 다음 베기를 준비한다.',
    temperament: '말은 적지만 상대를 얕보지 않는다. 잃어버린 것보다 지켜야 할 것을 먼저 본다.',
    movementNotes: '절제된 양손검 동작과 안정된 준비 자세. 외형을 이유로 별도 힘 보너스를 주지 않는다.',
    weaknesses: '큰 베기가 빗나간 뒤 몸 가까이 파고드는 연속 압박에는 빈틈이 생긴다.',
    ai: { level: 'normal', persona: {
      school: 'excalibur',
      level: { reaction: 0.26, guardChance: 0.7, counter: 0.35, feint: 0.2, followUp: 0.42, read: 0.75, discipline: 0.88, strength: 1, aggression: 0.8, windup: 0.7, skill: 0.82 },
      pers: { precision: 0.85, guardStick: 2.5, fearful: 0.2, angry: 0.2, dogged: 0.45, guardSpeed: 0.85, rhythm: 2.6, margin: 0.22, aggr: 0.85, vor: 0.45, patienceTime: 4.5, circleRate: 0.22,
        guardPref: { tagR: 1.6, pflugR: 1.5, ochsR: 1.1, langort: 1.2 },
        techPref: { zornhau: 1.5, oberhau: 1.25, zornhauL: 1.2, stichPflug: 1.1 } },
      idle: { guard: 'pflugR', gesture: 'still' }, close: { rate: 0.25, kind: 'barge', then: 'cut' },
    } },
    look: getLook('artoria'), lookVersion: CHARACTER_LOOK_VERSION.artoria,
    taunt: '이 검에 걸었던 맹세는, 아직 끝나지 않았습니다.',
    lines: { intro: ['이 검에 걸었던 맹세는, 아직 끝나지 않았습니다.', '왕관은 잃었어도, 지킬 것은 남았습니다.', '당신의 검으로 답해 주십시오.'], win: ['검을 거두세요. 여기서 끝냅시다.', '이름보다 무거운 것은, 그 이름의 약속입니다.', '나는 아직 돌아갈 곳이 있습니다.'] },
  },
  {
    id: 'tome', name: '토메 비달', epithet: '마지막 교습', age: 64,
    origin: '이탈리아 · 항구 도시의 검술 회랑', weapon: 'rapier', voice: 'liao',
    backstory: '귀족 자제에게 예절과 결투를 가르치던 검술사범. 제자를 잃은 뒤 회랑의 문을 닫았다. 이제 지워진 제자의 이름을 결투 명부에 되돌리려 마지막으로 칼을 든다.',
    want: '제자의 죽음을 무용담으로 팔아넘긴 후원자에게 진실을 인정받는 것.',
    school: '이탈리아 레이피어의 칼끝 위협과 간격 싸움에서 영감을 받은 창작 검객. 게임의 레이피어 유파를 사용한다.',
    signatureMoves: '칼끝을 오래 남겨 두었다가 상대의 큰 준비 동작에 찌르기를 겹친다.',
    favoriteGuards: '쟁기와 긴 자세. 큰 자세 전환보다 짧은 칼끝 이동을 선호한다.',
    temperament: '말투는 정중하지만 실수를 기다리는 눈은 냉정하다. 승부를 서두르지 않는다.',
    movementNotes: '넉넉한 간격, 적은 감기, 정확한 첫 찌르기. 반복 압박에는 회복할 공간이 필요하다.',
    weaknesses: '깊게 붙어 칼끝을 지나치거나 연속 압박으로 물러날 길을 막으면 긴 준비 간격이 약점이 된다.',
    ai: { level: 'normal', persona: {
      school: 'rapier',
      level: { reaction: 0.25, guardChance: 0.76, counter: 0.48, feint: 0.22, followUp: 0.32, read: 0.84, discipline: 0.94, strength: 0.9, aggression: 0.72, windup: 0.64, skill: 0.88 },
      pers: { precision: 0.92, guardStick: 3.5, fearful: 0.32, angry: 0.12, dogged: 0.25, guardSpeed: 0.68, rhythm: 3.6, margin: 0.25, aggr: 0.75, vor: 0.28, patienceTime: 5.6, circleRate: 0.2,
        guardPref: { pflugR: 1.8, pflugL: 1.3, langort: 2.1, tag: 0.3, tagR: 0.3 },
        techPref: { stichPflug: 2.5, stichPflugL: 1.8, stichOchs: 1.5, stichOchsL: 1.3, oberhau: 0.4, zornhau: 0.5, zwerch: 0.5 } },
      idle: { guard: 'pflugR', gesture: 'still' }, close: { rate: 0.15, kind: 'barge', then: 'none' },
    } },
    look: getLook('tome'), lookVersion: CHARACTER_LOOK_VERSION.tome,
    taunt: '서두르지 마시오. 실수는 한 번이면 충분하니.',
    lines: { intro: ['서두르지 마시오. 실수는 한 번이면 충분하니.', '칼끝을 보시오. 내 얼굴 말고.', '오늘은 내가 마지막으로 가르칠 차례군.'], win: ['물러설 곳까지 보고 들어왔어야지.', '좋은 질문이었소. 답은 조금 늦었지만.', '다음엔 이름을 먼저 묻겠소.'] },
  },
  {
    id: 'omari', name: '오마리', epithet: '빚 없는 선장', age: 51,
    origin: '아프리카 동해안 · 인도양의 산호 항구', weapon: 'falchion', voice: 'bran',
    backstory: '상인의 배에서 밧줄을 잡던 소년은 선장이 됐고, 끝내 남의 깃발 아래 항해하기를 그만뒀다. 항구는 그를 해적이라 부른다. 그는 빚에 묶인 선원들의 몸값을 사들이며 다시 바다로 나갈 배를 마련한다.',
    want: '마지막 선원까지 빚에서 풀어 주고, 누구에게도 소유되지 않은 배를 띄우는 것.',
    school: '좁은 갑판의 짧은 베기와 밀어붙이기에서 영감을 받은 창작 검객. 기존 펄션 유파를 사용한다.',
    signatureMoves: '가까이 붙어 비스듬히 베고, 막히면 박자를 바꿔 다시 들어간다.',
    favoriteGuards: '오른쪽 어깨와 옆 지킴. 칼을 숨겼다가 짧게 되돌리는 자세.',
    temperament: '웃으며 거래를 제안하지만 싸움이 시작되면 실용적이다. 체면보다 살아 돌아가는 쪽을 고른다.',
    movementNotes: '토메보다 좁은 간격과 잦은 압박. 짧은 무기의 거리 손해를 접근으로 해결하려 한다.',
    weaknesses: '접근 전에 긴 칼끝을 반복해서 만나면 불리하다. 공격 욕심 때문에 재진입이 읽힌다.',
    ai: { level: 'normal', persona: {
      school: 'falchion',
      level: { reaction: 0.28, guardChance: 0.58, counter: 0.28, feint: 0.32, followUp: 0.57, read: 0.66, discipline: 0.72, strength: 1.05, aggression: 0.9, windup: 0.84, skill: 0.73 },
      pers: { precision: 0.74, guardStick: 1.65, fearful: 0.3, angry: 0.38, dogged: 0.58, guardSpeed: 0.82, rhythm: 2.1, margin: 0.2, aggr: 0.95, vor: 0.63, patienceTime: 3.6, circleRate: 0.34,
        guardPref: { tagR: 1.5, wechselR: 1.5, pflugR: 1.1 },
        techPref: { zornhau: 1.7, zornhauL: 1.3, oberhau: 1.1, zwerch: 1.4, unterhau: 1.2, stichPflug: 0.65 } },
      idle: { guard: 'tagR', gesture: 'settle' }, close: { rate: 0.5, kind: 'barge', then: 'cut' },
    } },
    look: getLook('omari'), lookVersion: CHARACTER_LOOK_VERSION.omari,
    taunt: '배는 내가 몰지. 내 삶도 마찬가지야.',
    lines: { intro: ['배는 내가 몰지. 내 삶도 마찬가지야.', '몸값은 안 받는다. 길만 비켜.', '바람이 바뀌기 전에 끝내자고.'], win: ['빚은 여기서 끝이다.', '살아 있으면, 다음 항구에서 보자.', '우리 배에 빈자리는 있어. 족쇄는 없고.'] },
  },
  {
    id: 'yeongman', name: '영만', epithet: '숲이 부른 이름', age: 19,
    origin: '일본 · 오래된 신목이 선 산골', weapon: 'monohoshizao', voice: 'isolde',
    backstory: '신목 아래 작은 사당을 돌보는 열아홉 살 무녀. 장마 뒤 숲을 베어 길을 내겠다는 사람들이 찾아오자, 사당에 남은 긴 칼을 들고 처음으로 산을 내려왔다. 나무와 물의 길에는 밝지만 사람의 싸움에는 아직 서툴다.',
    want: '마을의 물길과 신목을 지키고, 돌아와 다시 평범한 아침을 맞는 것.',
    school: '긴 일본도의 거리와 큰 베기에서 영감을 받은 창작 검객. 무녀의 역사적 실전 검술을 재현했다는 뜻은 아니다.',
    signatureMoves: '긴 칼이 닿는 자리에서 망설이다, 한 번 결심하면 크게 비스듬히 벤다.',
    favoriteGuards: '오른쪽 지붕과 높은 준비 자세. 긴 칼을 몸 가까이 회수한다.',
    temperament: '조용하고 단호하다. 숲을 위해서는 물러서지 않지만 다친 상대를 보는 일에는 익숙하지 않다.',
    movementNotes: '긴 사거리와 절제된 공격 횟수. 큰 베기를 쓴 뒤 다음 준비가 읽히는 젊은 검객.',
    weaknesses: '큰 공격을 비켜선 뒤 안쪽으로 파고들면 다음 자세를 되찾기 어렵다. 속임수를 읽는 경험이 적다.',
    ai: { level: 'normal', persona: {
      school: 'monohoshizao',
      level: { reaction: 0.33, guardChance: 0.57, counter: 0.18, feint: 0.06, followUp: 0.3, read: 0.48, discipline: 0.84, strength: 0.94, aggression: 0.7, windup: 0.94, skill: 0.65 },
      pers: { precision: 0.73, guardStick: 2.8, fearful: 0.4, angry: 0.2, dogged: 0.34, guardSpeed: 0.67, rhythm: 3.7, margin: 0.36, aggr: 0.74, vor: 0.38, patienceTime: 5, circleRate: 0.18,
        guardPref: { tagR: 2, tag: 1.65, ochsR: 0.8 },
        techPref: { zornhau: 1.6, oberhau: 1.65, zornhauL: 1.3, unterhau: 0.65, stichPflug: 0.6, stichOchs: 0.65 } },
      idle: { guard: 'tagR', gesture: 'still' }, close: { rate: 0.2, kind: 'barge', then: 'none' },
    } },
    look: getLook('yeongman'), lookVersion: CHARACTER_LOOK_VERSION.yeongman,
    taunt: '여기서부터는 지나갈 수 없어요.',
    lines: { intro: ['이 숲은 내줄 수 없어요.', '나무를 다치게 하진 말아요.', '무서워도, 물러서진 않아요.'], win: ['…이제 숲으로 돌아갈래요.', '더는 다치게 하고 싶지 않아요.', '아직 물소리가 들려요.'] },
  },
];
