// Generated by tools/sim/morgenstern_design.mjs --write-source.
// Physical dimensions and mass properties for the 69 cm user-requested reconstruction.
const freeze = value => {
  if (value && typeof value === 'object') { Object.values(value).forEach(freeze); Object.freeze(value); }
  return value;
};
export const MORGENSTERN_DESIGN = freeze({
  "units": "metres, kilograms, kg*m^2",
  "construction": "Author reconstruction: 8 cm steel sphere, 70 mm blind socket, 10 mm top cap, 13 outward 25 mm conical spikes; wood frustum and steel grip sleeve.",
  "limitations": "The collar/head join and inherited cap/shaft overlap are geometric assembly approximations. Box shaft/ring colliders and the spherical spike envelope do not resolve surface detail; cap retains previous box inertia. This is not a structural-strength or historical-artifact validation.",
  "geometry": {
    "overallLength": 0.69,
    "bottom": -0.1015,
    "tip": 0.5885,
    "headCenter": 0.5235,
    "headRadius": 0.04,
    "spikeLength": 0.025,
    "spikeRadius": 0.007,
    "socketRadius": 0.02140356051103899,
    "socketBottom": -0.04,
    "socketTop": 0.03,
    "socketDepth": 0.07,
    "topCap": 0.01,
    "shaftBottom": -0.099,
    "shaftTop": 0.5535,
    "shaftLength": 0.6525,
    "steelDensity": 7800,
    "woodDensity": 635.3456684691199,
    "sleeveOuterRadius": 0.022
  },
  "lengthOnly": {
    "description": "Shorten the previous construction by 26.5 mm while preserving every part mass; no redistribution.",
    "parts": {
      "shaft": {
        "shape": [
          "box",
          0.017,
          0.32875,
          0.017
        ],
        "y": 0.22975,
        "mass": 0.371806390177327,
        "comY": 0.006639381884944926,
        "Ie": 0.013406752858798474,
        "It": 0.00005068958935792956,
        "volume": 0.0005625309625579104,
        "bottom": -0.099,
        "top": 0.5585,
        "bottomRadius": 0.016,
        "topRadius": 0.017,
        "density": 660.9527562477077
      },
      "butt": {
        "shape": [
          "box",
          0.0175,
          0.0015,
          0.0175
        ],
        "y": -0.1,
        "mass": 0.025,
        "comY": 0,
        "Ie": 0.000002570833333333334,
        "It": 0.000005104166666666668
      },
      "collar": {
        "shape": [
          "box",
          0.02,
          0.015,
          0.02
        ],
        "y": 0.4815,
        "mass": 0.1,
        "comY": 0,
        "Ie": 0.000020833333333333333,
        "It": 0.00002666666666666667
      },
      "head": {
        "shape": [
          "ball",
          0.053
        ],
        "y": 0.5235,
        "mass": 1.7031936098226732,
        "comY": 0.0007509135534327134,
        "Ie": 0.0012493731312126584,
        "It": 0.001467253667230174,
        "coreMass": 1.5731159660007883,
        "spikesMass": 0.13007764382188539,
        "holeVolume": 0.00006640103900366391,
        "socketRadius": 0.017,
        "socketTop": 0.035
      }
    },
    "aggregate": {
      "mass": 2.2,
      "comY": 0.4665644948467255,
      "Ie": 0.048092995818644235,
      "It": 0.001549714089921437,
      "handInertia": 0.5269943370921206
    }
  },
  "targetComY": 0.41990804536205295,
  "comRatio": 0.8999999999999998,
  "parts": {
    "shaft": {
      "shape": [
        "box",
        0.02140356051103899,
        0.32625,
        0.02140356051103899
      ],
      "y": 0.22725,
      "mass": 0.45868783689320664,
      "comY": 0.031204373872068945,
      "Ie": 0.01595891451881336,
      "It": 0.0000829924128405925,
      "volume": 0.0007219500496452988,
      "bottom": -0.099,
      "top": 0.5535,
      "bottomRadius": 0.016,
      "topRadius": 0.02140356051103899,
      "density": 635.3456684691199
    },
    "butt": {
      "shape": [
        "box",
        0.0175,
        0.0015,
        0.0175
      ],
      "y": -0.1,
      "mass": 0.025,
      "comY": 0,
      "Ie": 0.000002570833333333334,
      "It": 0.000005104166666666668
    },
    "collar": {
      "shape": [
        "box",
        0.023853280151722986,
        0.015000000000000013,
        0.023853280151722986
      ],
      "y": 0.4815,
      "mass": 0.1000000000000001,
      "comY": -0.00019000819714571149,
      "Ie": 0.000032542727833121715,
      "It": 0.000050093130029427184,
      "volume": 0.000012820512820512833,
      "bottom": 0.46649999999999997,
      "top": 0.4965,
      "outerRadius": 0.023853280151722986,
      "innerBottomRadius": 0.020683085776233793,
      "innerTopRadius": 0.020931525339959723,
      "density": 7800
    },
    "head": {
      "shape": [
        "ball",
        0.053
      ],
      "y": 0.5235,
      "mass": 1.4691857045598808,
      "comY": 0.002114186076737765,
      "Ie": 0.0011368879429466227,
      "It": 0.0013718689928106785,
      "coreMass": 1.339108060737996,
      "spikesMass": 0.13007764382188539,
      "holeVolume": 0.00009640205249889368,
      "socketRadius": 0.02140356051103899,
      "socketTop": 0.03
    },
    "sleeve": {
      "shape": [
        "box",
        0.022,
        0.013375742812404598,
        0.022
      ],
      "y": -0.0856242571875954,
      "mass": 0.1471264585469126,
      "comY": -0.0000709025619091842,
      "Ie": 0.00003612196517329922,
      "It": 0.00005469735366953082,
      "volume": 0.00001886236648037341,
      "bottom": -0.099,
      "top": -0.07224851437519081,
      "outerRadius": 0.022,
      "innerBottomRadius": 0.016,
      "innerTopRadius": 0.01622153758058827,
      "density": 7800
    }
  },
  "aggregate": {
    "mass": 2.2,
    "comY": 0.4199080453620529,
    "Ie": 0.09028539864208118,
    "It": 0.0015647560560168956,
    "handInertia": 0.47819548507359694
  }
});
